### ISSUE TITLE
时间无法拖动筛选-dll

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#100]
步骤：
http://52.83.102.127:8090/#/app/5/dashboard/4/chart/269
数据集
1、结账时间为维度
2、对结账时间进行筛选

结果：
无法拖动选择

期望：
时间可以拖动筛选

**Comment by ThomasChan** [comment]
schema min max 解析失败

**Comment by linhualai** [comment]
@janplus valueset/min/max 的 issue 你来fix.

**Comment by wwgracie** [comment]
应该已经fix了，可以重试一下或者等升级后重试。
