### ISSUE TITLE
司宇：发布后的图表可以删除筛选条件

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#103]
步骤：
1. 将探索进行发布
2. 进入应用查看发布的仪表盘
3. 选择有筛选条件的图表打开
4. 删除筛选条件
结果：
可以删除筛选条件
期望：
发布的应用不可以修改
![061404](https://user-images.githubusercontent.com/39791844/41390756-a06fc28c-6fc9-11e8-9c9d-8083d4fb3289.gif)

**Comment by xuyian252** [comment]
前端：
1、删除操作后，无论返回结果是否成功，页面都会将所选筛选条件隐藏
2、是否应该隐藏筛选条件的删除操作按钮
@MarshallChen

**Comment by MarshallChen** [comment]
应该隐藏删除按钮
