### ISSUE TITLE
杨慧[block] : 追加合并报错

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#107]
![image](https://user-images.githubusercontent.com/39791844/41446906-e9b84886-7084-11e8-9f61-f4efd2af68b4.png)
http://52.83.102.127:8090/#/app/2/dataset/42
1.追加合并选择字段报如图所示的错误.
2.右边的'已选字段'不能进行搜索

**Comment by weishishuo** [comment]
字段名列表|label|次数
---|---|---
 pwd_27_42,uuid_27_42      | uuid (27) (42)                                  | 2
 brid_37_42,brid_41_42     | 餐段id (42)                                     | 2
 rid_33_42,rid_41_42       | 理由id (42)                                     | 2
 bid_33,bid_33_42          | 品牌id (33)                                     | 2
 id_23_42,sid_32_42        | 主键id (42)                                     | 2
 ltid_33,ltid_33_42        | ltid (33)                                       | 2
 nsid_32_42,sid_41_42      | 桌台区域id (42)                                 | 2


label（字段管理页面看到的字段名）有重复。 奥琦玮那边有没有手动改过？

**Comment by weishishuo** [comment]
@cyberyoung

**Comment by weishishuo** [comment]
之前fusion编辑/新建可能有显示的字段名冲突，现在fix了。新部署版本后，你们需要重新建一下聚合数据集。旧的不会自动修复。

**Comment by firelyu** [comment]
![default](https://user-images.githubusercontent.com/1694674/42147378-0533fa82-7e00-11e8-917c-096d5ca8fcc8.gif)
1.首先重新聚合数据
2.聚合完成后自动实时更新
3.更新完成后一直点击'追加数据集',显示如上图所示得情况,一直闪退得那种感觉.

**Comment by weishishuo** [comment]
@firelyu ,这个时什么情况下触发的？
