### ISSUE TITLE
杨慧: 建图表选择对比维度显示'资源未找到'

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#108]
![image](https://user-images.githubusercontent.com/39791844/41447510-2d59d322-7088-11e8-8901-cb17c02c7b31.png)
如图, url:http://52.83.102.127:8090/#/app/2/dashboard/5/chart/377

**Comment by ThomasChan** [comment]
在操作该图表的时候，该图表已经被人删掉了

**Comment by ThomasChan** [comment]
不是 bug
