### ISSUE TITLE
杨慧:[bug] [block] 两张源表无法选择聚合筛选条件

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#11]
依然是之前出现的问题,两张源表无法选择聚合筛选条件,这些表都是随机的,没有特定说哪些表不能聚合,通常我选择某几个表进行聚合的时候,突然其中两张表就无法进行聚合条件的筛选了.
![image](https://user-images.githubusercontent.com/39791844/41025568-cf914430-69a4-11e8-89b4-7a63f8d2d566.png)
![_20180606161502](https://user-images.githubusercontent.com/39791844/41025574-d3e3663a-69a4-11e8-8075-9cfb6d559a0a.png)

**Comment by cyberyoung** [comment]
聚合o_dish这个数据集，后端未取到schema
当访问这个数据集时
![image](https://user-images.githubusercontent.com/501691/41025699-2c8a4c72-69a5-11e8-800e-8c917ddaaa57.png)

当聚合时，左侧栏list接口时
![image](https://user-images.githubusercontent.com/501691/41025736-509ada5a-69a5-11e8-92f2-41503a624378.png)

**Comment by zhaosy0415** [comment]
我重新将源表数据导进来,发现可以了,昨天也有这种情况,就是有的表之间不能进行条件关联的时候,重新导入表然后就可以了,这个聚合条件这块还是不稳定.
![image](https://user-images.githubusercontent.com/39791844/41028132-525092c6-69ab-11e8-8e09-6a432c87a477.png)

**Comment by cyberyoung** [comment]
应该好了，你们测试下

**Comment by zhaojunliRain** [comment]
Fix commit:
https://github.com/henglabs/everest/commit/d48b27c788e217968b4a0df6bda0f65356c8d093

henglabs/everest@d48b27c

**Comment by cyberyoung** [comment]
👌
