### ISSUE TITLE
杨慧:移动计算无法使用

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#110]
![image](https://user-images.githubusercontent.com/39791844/41447713-25f33974-7089-11e8-90e5-4812b18e68f4.png)
http://52.83.102.127:8090/#/app/2/dashboard/5/chart/379

**Comment by linhualai** [comment]
fixed. @zhaosy0415

**Comment by linhualai** [comment]
@zhaosy0415 移动计算累计计算大部分问题应该都fix了. 如果有几个图还是刷不出来, 可以尝试删掉, 再创建一个同样的图.  如果还是出错的话, 欢迎再报bug.
