### ISSUE TITLE
杨慧:[block] 仪表盘图表不能选择维度和数值等信息

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#112]
![image](https://user-images.githubusercontent.com/39791844/41753366-94f93c30-75ff-11e8-9d05-a7fa587749c1.png)
url:http://52.83.102.127:8090/#/app/37/dashboard/32/chart/494

**Comment by wwgracie** [comment]
点击字段右边的+号才能选中。

**Comment by zhaosy0415** [comment]
不是这个意思.是选择好的显示不到上面
![image](https://user-images.githubusercontent.com/39791844/41842281-ef3e376e-789c-11e8-9afb-9000cd78593d.png)

**Comment by firelyu** [comment]
1. 用户选择了9列数据。
2. 在下图方框中的编辑窗口，只显示了4列数据。用户不能编辑剩下5列数据的聚合方式。
![image](https://user-images.githubusercontent.com/1694674/41887078-cbb3b5cc-7931-11e8-88f9-b3668bcfb62c.png)

**Comment by ThomasChan** [comment]
http://52.83.102.127:8090/#/app/37/dashboard/32/chart/494
这个 chart 被删了？用哪个帐号登录？是 dll@acewill.cn 这个不？

**Comment by ThomasChan** [comment]
![image](https://user-images.githubusercontent.com/5715335/41890811-d3c37bfa-7943-11e8-80bb-2a1f2bff9b79.png)
 @zhaosy0415 你用的是哪个浏览器呀？这里如果选择了很多字段的话应该会出现滚动条的，看你们的描述是滚动条没有出现
