### ISSUE TITLE
杨慧:上传excel文件，数据数据行显示不一致

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#113]
从BDP导出excel表格,导入衡石,数据最终显示不一致

1. 从BDP中导出`yhy收银订单明细合表18012day`，上传到衡石。[ yhy收银订单明细合表18012day.xlsx](s3://hengshi-data/customers/acewill/issues/yhy收银订单明细合表18012day.xlsx)在S3中。

2. BDP显示的行数。
![image](https://user-images.githubusercontent.com/1694674/41757388-70a1179e-7614-11e8-88ad-00bbff6bd42a.png)

3. 衡石显示的行数。
![image](https://user-images.githubusercontent.com/1694674/41757404-7a1d2df8-7614-11e8-9942-9a5e5347d970.png)

**Comment by firelyu** [comment]
用excel打开文件，显示行数为`172670`，去掉表头，数据行为`172669`，行数显示正确。

需要杨慧确认BDP显示的问题。

![image](https://user-images.githubusercontent.com/1694674/41757441-aa0bbb56-7614-11e8-9777-1fdc30ae3cd6.png)
