### ISSUE TITLE
杨慧:if计算函数显示错误

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#114]
if (actionA || actionB,result1,result2)不能计算
,或者if(action in(数字,数字),result1,result2)不行了 ifelse也一样

**Comment by linhualai** [comment]
will be fix by henglabs/everest#1546

**Comment by wwgracie** [comment]
没有if函数了，有ifelse函数，用法：ifelse({rate_num} < 5,'差评','好评')

**Comment by firelyu** [comment]
![wechatimg319](https://user-images.githubusercontent.com/1694674/42213377-2788c892-7eeb-11e8-98f1-c1a28cfd53b3.png)

**Comment by wwgracie** [comment]
http://52.83.102.127:8090/#/app/50/dashboard/56/chart/705
if({活动金额}>0.00,1,if({活动金额}=0.00 and {商户实收总价}!=0.00,1,if({活动类型}=23,1,0)))
确实还有错。

**Comment by wwgracie** [comment]
@zhaosy0415  @firelyu 
使用
if({活动金额}>0.00,1,if({活动金额}=0.00 and {商户实收总价}!=0.00,1,if({活动类型}='23',1,0)))

**Comment by wwgracie** [comment]
@linhualai  提供更友好的错误信息
