### ISSUE TITLE
杨慧:打开某个探索报错,个别图表无法显示数据

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#115]
![image](https://user-images.githubusercontent.com/39791844/41827784-0cfdf444-7864-11e8-9442-34e7ef7eee05.png)

**Comment by wwgracie** [comment]
http://52.83.102.127:8090/#/app/24/dashboard/21 
报bug时加上链接会更便于dev复现、调试。

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/41885702-bc043a26-792b-11e8-95af-7bbb0e7a0ec1.png)
![image](https://user-images.githubusercontent.com/39791844/41885714-c830fb36-792b-11e8-853e-3a88529dc185.png)

**Comment by cyberyoung** [comment]
删除添加字段，重新来一次就好了 @zhaosy0415
