### ISSUE TITLE
杨慧:上传excel，不能识别成数字

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#117]
excel中的数字格式设置为数值,接着衡石导入该数据集,数据集显示格式为'文本',并且不能修改.

**Comment by firelyu** [comment]
`收银最终作图表1702月`中的`目标营业额`已经设置成数据格式，上传到衡石以后，只能识别成文字，不能修改成数字。

s3位置：s3://hengshi-data/customers/acewill/issues/收银最终作图表1702月.xlsx

**Comment by linhualai** [comment]
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/1201463/41961059-fe154704-7a23-11e8-8129-6e2e87c7a71b.png">

我直接detect引擎中的tb_xxx 是可以的. @cyberyoung 你看下为啥上传文件不行.

**Comment by zhaosy0415** [comment]
![default](https://user-images.githubusercontent.com/39791844/42016073-9f468666-7adc-11e8-832a-100f2c43b7fb.gif)
