### ISSUE TITLE
杨慧:仪表盘数值计算不准确

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#118]
1.   url: http://52.83.102.127:8090/#/app/37/dashboard/32/chart/501

同样的筛选条件,数值计算除了退菜率,其他都不正确.加上门店维度后,个别门店数据正确,但是总体门店数值不正确.

2.   url: http://52.83.102.127:8090/#/app/37/dashboard/32/chart/502

同样的筛选条件,以菜品类别为维度,菜品销售数量总体正确,但销售金额不正确.个别门店数据菜品销售数量和金额正确.

**Comment by ThomasChan** [comment]
@cyberyoung  解释一下

**Comment by zhaosy0415** [comment]
就是说筛选条件什么的都没有问题,只有退菜率能和BDP对应上, 总体的数值都不正确,然后添加了一个门店维度,个别门店维度的字段值能对的上.

**Comment by cyberyoung** [comment]
![image](https://user-images.githubusercontent.com/501691/42019677-4ea53462-7ae8-11e8-8a85-fd7bfa90a9b4.png)
![image](https://user-images.githubusercontent.com/501691/42019682-52e4c0ec-7ae8-11e8-814e-03fe3334cea1.png)

**Comment by cyberyoung** [comment]
![image](https://user-images.githubusercontent.com/501691/42019686-57bfb310-7ae8-11e8-8a6b-370a54a58789.png)
![image](https://user-images.githubusercontent.com/501691/42019691-5acb4f4c-7ae8-11e8-875d-721f377e5b3c.png)

**Comment by ThomasChan** [comment]
菜品分类这张图，    为什么我们的系统里的  “团购” 和 “套餐”  的 “菜品营业额” 是 0？而 BDP 里的 “团购” 的 “菜品营业额” 是 7053 ，“套餐” 的 “菜品营业额” 是 181298 ？

**Comment by ThomasChan** [comment]
@zhaosy0415

**Comment by ThomasChan** [comment]
麻烦仔细核对一遍数据

**Comment by zhaosy0415** [comment]
@ThomasChan 
1. 首先 这两个数据集的数据是一致的.也就是说数据源没有问题
![image](https://user-images.githubusercontent.com/39791844/42070440-fc921bb2-7b88-11e8-89c4-1795d25177d4.png)
![image](https://user-images.githubusercontent.com/39791844/42070474-24d5440a-7b89-11e8-8b8a-7081f570ec8b.png)
2.“团购” 和 “套餐” 的 “菜品营业额” 是 0?这不就是数据不准确吗?数据集一样,维度一样,筛选条件一样.然后你们为什么显示的就不正确?这本身就是我提的这个问题.
