### ISSUE TITLE
【需求】司宇：建议在高级计算页面，增加公式的示例和解释

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#12]
![image](https://user-images.githubusercontent.com/39791844/41026328-d9b84ab0-69a6-11e8-9af3-63920c8bb4d8.png)
对于公式，不能掌握正确的使用方法和格式

**Comment by MarshallChen** [comment]
https://github.com/henglabs/lhotse/commit/4dd67ed9aa3185b40b9579da20febb60253659db
