### ISSUE TITLE
杨慧:添加计算字段报错

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#121]
![image](https://user-images.githubusercontent.com/39791844/41841666-79c73d24-789b-11e8-860b-ad41dec2f8f3.png)
http://52.83.102.127:8090/#/app/24/dashboard/34/chart/530

**Comment by ThomasChan** [comment]
这个图被删掉了？ @zhaosy0415

**Comment by zhaosy0415** [comment]
有好几个图都有这种情况,就是原来某个指标一删除就出现上面提示的sql语句错误.
