### ISSUE TITLE
杨慧:累计计算不同维度计算错误

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#123]
url:http://52.83.102.127:8090/#/app/37/dashboard/35/chart/535
维度切换成周的时候,累计计算是错误的.没有反应
![image](https://user-images.githubusercontent.com/39791844/41886909-f1fb6b9a-7930-11e8-8494-8d6eea20f73c.png)
但是切换成天,计算就正确了.

**Comment by ThomasChan** [comment]
Blocked by henglabs/everest#1480

**Comment by ThomasChan** [comment]
等重新部署后重新试一下。

**Comment by zhaosy0415** [comment]
第一次验证有效果，能累计计算，第二次就又没效果了，这里选年和季度都不累计计算
![image](https://user-images.githubusercontent.com/39791844/42865891-a5ffb330-8a9d-11e8-9852-6f2f8a683258.png)

![image](https://user-images.githubusercontent.com/39791844/42865971-dcdcc23a-8a9d-11e8-916a-0b2a5eabed35.png)

**Comment by zhaosy0415** [comment]
原因是，只要这张Excel里我添加了计算字段就会出现这种情况
![image](https://user-images.githubusercontent.com/39791844/42867080-12847164-8aa1-11e8-8864-91ec54f00d62.png)

**Comment by ThomasChan** [comment]
@linhualai

**Comment by wwgracie** [comment]
已fix，等升级后就可以了。
