### ISSUE TITLE
杨慧:新建探索报'执行sql失败'

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#125]
http://52.83.102.127:8090/#/app/18/dashboard/10/chart/546
![image](https://user-images.githubusercontent.com/39791844/41963101-51451986-7a29-11e8-8c68-2333a2054b4c.png)

**Comment by linhualai** [comment]
@zhaosy0415 历史遗留bug, 数据重新导入就可以了.

**Comment by zhaosy0415** [comment]
数据集重新导入是吗?
