### ISSUE TITLE
杨慧:累计计算能否增加'天'和'小时'的粒度

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#126]
![image](https://user-images.githubusercontent.com/39791844/42008618-1cdbaf8a-7ab9-11e8-8dcc-5aee976b6072.png)
没有天和小时的粒度.希望可以添加上去.

**Comment by wwgracie** [comment]
@zhaosy0415  维度聚合选“时“时，累计计算会出现“天”，可以按天累计计算。
按小时累计还没有加上去，稍后应该会加上去。

**Comment by zhaosy0415** [comment]
@wwgracie ![new](https://user-images.githubusercontent.com/39791844/42368523-d64332a0-8139-11e8-830e-3200a8ee4ce1.gif)
选择小时,累计计算出现'天'.这个确实出现了.但是后面得累计计算还是按小时累计得,也就是说这个设置并没有生效,把累计计算 粒度改成其他也是如此, 实际上我们希望得是后面的累计计算可以和前面得粒度一样同步.比如说维度选择时间 然后粒度选择月,那么累计计算得时候下拉菜单也要有月.

**Comment by ThomasChan** [comment]
@hhmob 解释一下这个功能，我被你们说晕了

**Comment by hhmob** [comment]
累积计算的“重复周期”一定需要大于时间维度的聚合单位的，比如你时间维度是按“天”聚合的，那么重复周期就只支持“周月季年”，这时“天”作重复周期是没意义的。
累积计算“重复周期”的作用是：计算时会根据设置在每个重复周期的起点清零并重新计算。

那么就是说，如果你时间维度选择“月”，累积计算“重复周期”也选成“月”，比如计算方式是“求和”，那么这等价于按“月”“求和”，不需要用到累积计算。BDP也是不支持的。
