### ISSUE TITLE
邓凯红-表格设置合并单元格不能取消，勾选总计却不显示总计

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#127]
![image](https://user-images.githubusercontent.com/39791844/42010924-91f62fd4-7ac3-11e8-9efc-31015f09191c.png)
步骤：
1.表格设置中的合并单元格前面的勾选无法取消掉（在我的电脑上操作不行，别人的电脑可以）
2.行总计和列总计勾选后没有显示总计（这个是我们操作了都不显示）
结果：
无
期望：
1.能正常操作
2.能正常显示

**Comment by ThomasChan** [comment]
@zhaosy0415 麻烦给一下该图表的 URL 地址，我想看一下

**Comment by zhaosy0415** [comment]
http://52.83.102.127:8090/embed/#/12d0e91cbc208c7a4c57e694b27fe0c4

**Comment by ThomasChan** [comment]
不能复现。
