### ISSUE TITLE
杨慧:计算同环比中得对比值时候,对比值随着维度改变,而没有其他选择.

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#129]
![default](https://user-images.githubusercontent.com/39791844/42148132-983d8746-7e03-11e8-996f-498eed2f7338.gif)

**Comment by ThomasChan** [comment]
没看懂什么意思，什么是 “没有其他选择” ？ @zhaosy0415

**Comment by firelyu** [comment]
![wechatimg288](https://user-images.githubusercontent.com/1694674/42156121-c6cb1c0e-7e1c-11e8-98dd-b9d184fea2de.png)

**Comment by ThomasChan** [comment]
这里没有下拉的原因是：
你已经在轴上选择了日期的聚合，那么随着你更改日期的聚合函数，日期偏移的粒度也是随之改变的。

@hhmob 解释一下为什么是这样的设计。

**Comment by hhmob** [comment]
设计就是这样，选择了“天”作为时间维度的聚合单位，那么在同环比里面可以选择多种对比类型，你展示的“时间偏移”的设置只是“对比类型”选定为“对比相对日期”时出现。你当然还可以环比，可以对比上周同期，上月同期和上年同期。如下图所示：

![image](https://user-images.githubusercontent.com/15355269/42234455-33166ce6-7f27-11e8-9bff-a66f7199ffa0.png)
