### ISSUE TITLE
司宇：追加数据表，类型相同的字段提示是冲突字段

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#131]
![image](https://user-images.githubusercontent.com/39791844/42150682-23a09c52-7e0d-11e8-8329-2c09c1e7a957.png)
![image](https://user-images.githubusercontent.com/39791844/42150693-26bc5a20-7e0d-11e8-9a22-fbd4d4b53c5c.png)
![image](https://user-images.githubusercontent.com/39791844/42150699-298e3e80-7e0d-11e8-852b-f49c99556b2e.png)

**Comment by wwgracie** [comment]
@imzhangjunjie  赶快看一下。

**Comment by imzhangjunjie** [comment]
Fix commit:
henglabs/everest@fe43d24ea506a0690db197ecee78f3b2e88f2454

**Comment by zhaosy0415** [comment]
验证通过
