### ISSUE TITLE
【徐晓凤】成本金额字段的高级计算没有重复率、活跃率、留存率

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#132]
![image](https://user-images.githubusercontent.com/39791844/42151508-d2715fee-7e0f-11e8-89da-861d07a3ba39.png)

http://52.83.102.127:8090/#/app/37/dashboard/48/chart/599

**Comment by wwgracie** [comment]
只有整数、文本才有重复率、活跃率、留存率

**Comment by linhualai** [comment]
重复率, 活跃率、留存率 讲的是用户维度的统计. 

金额从逻辑上谈不上重复率活跃率留存率(金额没有重复访问一说), 所有从产品上隐藏了这个功能, 防止用户误操作. @zhaosy0415

**Comment by hhmob** [comment]
老赖解释的比较到位了，我讲一下使用经验：通常把表示ID的字段（比如身份证号，门店名，员工号，手机号，菜品名，VIP卡号）用来做重复率，活跃率和留存率才是有意义的。大家把握这个大原则做这方面的分析吧。
