### ISSUE TITLE
司宇：追加的数据集不显示行数和大小

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#133]
![image](https://user-images.githubusercontent.com/39791844/42151520-dde49008-7e0f-11e8-990f-d70c35cd68a0.png)
http://52.83.102.127:8090/#/app/44/dataset/614

**Comment by wwgracie** [comment]
等升级后验证一下。

**Comment by zhaosy0415** [comment]
问题仍存在
![image](https://user-images.githubusercontent.com/39791844/42255651-58829600-7f7f-11e8-9872-e2195b295cd9.png)

**Comment by wwgracie** [comment]
@weishishuo 解释一下
