### ISSUE TITLE
杨慧:点击'过滤条件'按钮没反应?

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#134]
![default](https://user-images.githubusercontent.com/39791844/42152050-95e4d7f2-7e11-11e8-9280-d2103229cc4e.gif)

**Comment by ThomasChan** [comment]
@zhaosy0415 麻烦给一下该图表的 url

**Comment by zhaosy0415** [comment]
@ThomasChan http://52.83.102.127:8090/#/app/37/dashboard/32/chart/612

**Comment by ThomasChan** [comment]
Fixd by https://github.com/henglabs/lhotse/commit/68f39769af14703ff901dde714641009924aa58a

**Comment by ThomasChan** [comment]
等重新部署后重新试一下
