### ISSUE TITLE
司宇：图表中度量升降序不正确

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#136]
![image](https://user-images.githubusercontent.com/39791844/42152955-44ad0500-7e14-11e8-94a8-4bb5e6fbc6d3.png)
![image](https://user-images.githubusercontent.com/39791844/42152977-54c645f0-7e14-11e8-8719-f779230ae027.png)

**Comment by ThomasChan** [comment]
已修复，等重新部署后重新试一下

**Comment by zhaosy0415** [comment]
验证通过
