### ISSUE TITLE
杨慧:留存率显示问题

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#137]
url:http://52.83.102.127:8090/#/app/37/dashboard/32/chart/612
![image](https://user-images.githubusercontent.com/39791844/42154481-720ef31a-7e18-11e8-97fe-972b2747545a.png)
![default](https://user-images.githubusercontent.com/39791844/42154494-797fb166-7e18-11e8-86ba-a2128e8954ad.gif)

**Comment by hhmob** [comment]
和BDP的是一个意思哈
