### ISSUE TITLE
邓凯红-创建图表时无法显示数据集中已有的数据

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#145]
![image](https://user-images.githubusercontent.com/39791844/42202709-f4b306ce-7ece-11e8-9cdd-ff735e07db08.png)

![image](https://user-images.githubusercontent.com/39791844/42202624-af0b4f64-7ece-11e8-9103-5e6cade014de.png)
步骤：
1.查看数据集，单据类型为“库存表”的数量和小计有数据
2.创建图表
结果：
1.创建Excel表格，以单据类型为维度时，没有库存表
2.创建KPI图表，过滤单据类型为库存表，结果为null
期望：
正常显示，有数据

**Comment by ThomasChan** [comment]
这里有几个问题

1. 字段 `制单时间` 在数据集里隐藏了，但是在图表的时间轴上还存在，这是个问题，修复了
2. 时间字段默认是过滤 `所有有效时间`，所以不论是 `制单时间` 还是 `审核时间` 都会正好过滤掉 `库存表` 那一行数据

**Comment by zhaosy0415** [comment]
嗯嗯，明白了
