### ISSUE TITLE
杨慧 [bug] concat函数不支持数值格式

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#15]
如题,fusion表中无法使用concat,源表可以.

**Comment by weishishuo** [comment]
concat的bug今天fix了

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/41082017-7040201c-6a5f-11e8-92dc-80e3d8e2f5b6.png)
字段来源于excel表.

**Comment by iamtianyuan** [comment]
现在TiDB上的数据，不管是否导入引擎，文本和数字类型都可以使用concat了

**Comment by wwgracie** [comment]
请加UT。@iamtianyuan

**Comment by iamtianyuan** [comment]
b2e97e2

**Comment by wwgracie** [comment]
#b2e97e2bbf5277fff0ce3ff9f03d2b6353db2505

**Comment by wwgracie** [comment]
henglabs/everest@5851430
