### ISSUE TITLE
公式计算有误-dll

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#155]
http://52.83.102.127:8090/#/app/5/dashboard/46/chart/683
distinct_count({订单id})/(max({门店桌台总数})*distinct_count(date({结账时间})))
分子/分母   计算错误，详细见图。

**Comment by wwgracie** [comment]
@ThomasChan  我感觉算的是对的啊
<img width="867" alt="2018-07-03 6 52 08" src="https://user-images.githubusercontent.com/38898981/42215804-359ff5ac-7ef2-11e8-84bb-5392b83e1637.png">

**Comment by zhaosy0415** [comment]
麻烦计算一下4975/1100=2826.70?   咱们计算公式不考虑优先级么?

**Comment by wwgracie** [comment]
@zhaosy0415  不好意思。
@linhualai  赶快看一下。
