### ISSUE TITLE
邓凯红-year、month、day、minute和second函数返回值类型改为整数，分别只返回日期里面的年，月、日、分、秒

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#156]
比如原字段{审核时间}，其中值为“2018-02-05 14:23:52”的结果如下
year({审核时间})=2018
month({审核时间})=2
day({审核时间})=5
minute({审核时间})=14
second({审核时间})=23

**Comment by iamtianyuan** [comment]
前三个可以用如下的函数：
yoy({审核时间}) => yearofyear
moy({审核时间}) => monthofyear
dom({审核时间}) => dayofmonth

minuteofhour和secondofminut暂时还没有

**Comment by zhaosy0415** [comment]
好的，看到了
