### ISSUE TITLE
【徐晓凤】concat函数使用不规范系统报错例如写入concat({订单id}{门店id (581)})，系统报错

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#159]
![image](https://user-images.githubusercontent.com/39791844/42209469-46f92aa0-7ee1-11e8-981a-ede95fba6b7a.png)

**Comment by wwgracie** [comment]
@linhualai  去掉后面内部代码部分，只保留前面的出错信息。

**Comment by wwgracie** [comment]
#171  同一个问题。

**Comment by linhualai** [comment]
已提供更明确的错误位置.

**Comment by wwgracie** [comment]
还有一点小问题，后续会改得更友好。
