### ISSUE TITLE
司宇：上传的excel，建立图表之后，再追加excel，报错，不清楚错误信息表达的意图

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#161]
![image](https://user-images.githubusercontent.com/39791844/42209294-dcd6c146-7ee0-11e8-9f3b-76710850e501.png)
步骤：
1. 导入excel，http://52.83.102.127:8090/#/app/44/dataset/679
2. 创建一些图表
3. 追加另一个excel
结果：
报错，而且从报错信息看不出是哪一列有问题
期望：
追加成功

**Comment by weishishuo** [comment]
这个估计是某列类型有冲突，我们提示信息不够清晰。我们也不知道你那边的文件是什么样的。能给我们一份吗？

**Comment by weishishuo** [comment]
提示信息我们会优化一下。

**Comment by firelyu** [comment]
新上传的Excel文件中，更改了一列的数据类型。

**Comment by weishishuo** [comment]
新版本我们提示更明确。下一个版本更新就好了。
