### ISSUE TITLE
【徐晓凤】if函数使用字段is null，系统报错，具体例子

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#162]
if({订单id} is null,{订单id},0)
http://52.83.102.127:8090/#/app/37/dataset/607

**Comment by wwgracie** [comment]
不支持is null，支持if(isnull({订单id}),{订单id},0)

**Comment by zhaosy0415** [comment]
@wwgracie 
![if isnull](https://user-images.githubusercontent.com/39791844/42260065-966d1f4c-7f95-11e8-88b6-f40370ad1271.gif)

**Comment by linhualai** [comment]
@zhaosy0415 表达式不能乱写啊.
`{退单理由}` 不是整数吧, 
if(xxx, '理由1', 0)
0 和 `'理由1'`  它不是一个类型, 
你是不是想要写 `NULL` 或者 `''`?
