### ISSUE TITLE
邓凯红-substring改为可以截取日期字段

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#163]
![image](https://user-images.githubusercontent.com/39791844/42210425-96da27a2-7ee3-11e8-89ca-ba62ba687bd7.png)

{审核时间}为“2018-02-15 14:23:52”时 可以返回以下值
substring({审核时间},9,2)=15
substring({审核时间},6,2)=02

**Comment by iamtianyuan** [comment]
用dom()和moy吧，分别是dayofmonth和monthofyear
这两个函数返回的都是整数类型。

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/42252699-66285d80-7f70-11e8-853a-4efa23bc02e1.png)
试用了可以，您添加到函数列表里面吧，不然我们不知道还可以这样使用

**Comment by zhaosy0415** [comment]
好的，看到了他们的简写了
