### ISSUE TITLE
司宇：追加后的数据集不能删除

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#166]
![image](https://user-images.githubusercontent.com/39791844/42211541-725aa6ce-7ee6-11e8-881c-92c22a046076.png)
该数据集没有再追加其他的数据集

**Comment by imzhangjunjie** [comment]
Fix commit:
henglabs/everest@17aa8fdab303e2c1e6477741c93070e90fcc6dcc

**Comment by zhaosy0415** [comment]
仍无法删除

**Comment by wwgracie** [comment]
@weishishuo 能看一下吗？

**Comment by weishishuo** [comment]
再升级一版就行，今天的版本更新有问题。
