### ISSUE TITLE
杨慧 [bug] [block] 聚合后无法操作下一步

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#17]
如题,图片无法上传,具体情况是这样的:聚合后点击'数据预览' ,接着报空指针异常

**Comment by cyberyoung** [comment]
![image](https://user-images.githubusercontent.com/501691/41030708-77f403ea-69b1-11e8-94a5-7d67d6a303ca.png)

**Comment by weishishuo** [comment]
能不能把你们的账户开放给我们看看？或者把"收银工作表"应用协作给hengshi_test账户？

**Comment by zhaosy0415** [comment]
已经协作给hengshi_test了.

**Comment by weishishuo** [comment]
fixed
