### ISSUE TITLE
杨慧:横向柱状图没有排序按钮?

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#170]
![image](https://user-images.githubusercontent.com/39791844/42256087-a0efc3a2-7f81-11e8-8715-f63b42813265.png)

**Comment by wwgracie** [comment]
@zhaosy0415  有的，看图
<img width="1432" alt="2018-07-04 4 00 11" src="https://user-images.githubusercontent.com/38898981/42264506-5e0480b0-7fa3-11e8-95f1-1099f558b040.png">
