### ISSUE TITLE
邓凯红-公式报错原因不明确

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#171]
![image](https://user-images.githubusercontent.com/39791844/42260231-351e23e8-7f96-11e8-91a7-b5b385bde5f6.png)
图中的错误是因为没有添加单引号，或者写成双引号，都会报错，而异常提示没有指明是什么原因

期望：
异常提示提示具体错误

**Comment by wwgracie** [comment]
@zhaosy0415 
错误消息里的column 30 就是第30个字符，就是“期”这个字符处，缺少一个字符。
之后会让@lailinhua 修改的更明确一些。

**Comment by linhualai** [comment]
已提供更明确的错误位置.

**Comment by wwgracie** [comment]
@linhualai  错误消息后半部分需要更明确。
<img width="1146" alt="2018-07-05 10 35 06" src="https://user-images.githubusercontent.com/38898981/42299702-29fad714-803f-11e8-9590-ffb3d0daf88b.png">
