### ISSUE TITLE
司宇：聚合表创建副本报错

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#173]
![image](https://user-images.githubusercontent.com/39791844/42301567-9fda3b6a-8048-11e8-9dc3-312dc08d43c8.png)

步骤：
1. 创建一个聚合表
2. 创建聚合表副本
结果：
报错
期望：
成功创建副本

**Comment by weishishuo** [comment]
fixed

**Comment by weishishuo** [comment]
这个已经修复了，现在还会复现吗？
