### ISSUE TITLE
司宇：编辑聚合表，增加合表，然后保存，会增加一个报错的副本，然后又消失

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#176]
![image](https://user-images.githubusercontent.com/39791844/42306344-33e9b516-8061-11e8-8d6f-c12068455d20.png)
![image](https://user-images.githubusercontent.com/39791844/42306347-366fc708-8061-11e8-91ff-0f7fdcb1fff5.png)
![image](https://user-images.githubusercontent.com/39791844/42306349-3896eb7e-8061-11e8-9dd6-22cdf69ede77.png)

**Comment by weishishuo** [comment]
那个是我测试创建副本的bug，我自己删了。。。
