### ISSUE TITLE
邓凯红-添加时间字段为维度时默认按月

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#180]
![image](https://user-images.githubusercontent.com/39791844/42310314-b11a27bc-806d-11e8-9922-ffe2d770d28b.png)
步骤：
1.添加时间字段为维度时，默认是毫秒展示
结果：
1.实际情况是很少会出现以毫米展示维度的需求，所以每次都要修改
期望：
1.添加时间字段为维度时默认按月
![image](https://user-images.githubusercontent.com/39791844/42310540-421ec4d4-806e-11e8-80ed-d84dcf3c6fdf.png)

**Comment by ThomasChan** [comment]
首先  @zhaosy0415  你在导入该数据集的时候，在 `配置数据` 那一步，就可以给每个字段选择默认聚合。
其次 @hhmob 我们可以修改一下数据集字段管理页面，加上修改字段默认聚合的下拉选项。

**Comment by hhmob** [comment]
@MarshallChen thomas的建议不错，我们来看看字段管理页面还可以放下默认聚合的下拉不？

**Comment by hhmob** [comment]
已经可以在字段管理页面调整字段的默认聚合方式，请在下一版本中验证
