### ISSUE TITLE
不能连上MySQL数据库

### ISSUE THREAD

**Issue by firelyu** [henglabs/issues#181]
使用命令行可以连上，在页面中不能连上。

```
$ mysql -h123.206.31.210 -P3306 -ubdp alipos -pbdp321@123 -A
mysql> 
```

![image](https://user-images.githubusercontent.com/1694674/42311175-cb567a5c-806f-11e8-8b78-020397d4b913.png)

**Comment by firelyu** [comment]
数据库和BI都在AWS上。
登录BI机器，可以通过命令行连上数据库。
![image](https://user-images.githubusercontent.com/1694674/42311688-0601d1b4-8071-11e8-82ab-857d81443e1e.png)

**Comment by firelyu** [comment]
在develop.hengshi.io上，使用TiDB，端口改成3306，可以连上。
![image](https://user-images.githubusercontent.com/1694674/42311971-adde3a26-8071-11e8-9db1-1596f517414b.png)

**Comment by weishishuo** [comment]
为了支持高级计算，mysql需要创建udf的权限，tidb不支持udf，所以才不报错，能不能让他们增加权限？

**Comment by weishishuo** [comment]
当前mysql连接需要创建udf的权限，参考语句
```
grant alter routine,create routine,execute on {database}.* to {user}
```

**Comment by weishishuo** [comment]
fixed，下一个版本更新就好了。
