### ISSUE TITLE
司宇：KPI计数结果不正确

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#182]
http://52.83.102.127:8090/#/app/51/dashboard/62/chart/779
http://52.83.102.127:8090/#/app/51/dataset/727
步骤：
1. 使用员工信息表（1）创建KPI图表
2. 选择员工姓名，计数
结果：
显示76
期望：
该表有一千多行数据，没有选择去重，单纯计数应该是一千多而不是76

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/42314563-e5bdbcc2-8077-11e8-856d-97197f85db40.png)
![image](https://user-images.githubusercontent.com/39791844/42314594-f35c3354-8077-11e8-8ae3-78efd28be06d.png)

**Comment by zhaosy0415** [comment]
咱们的系统默认筛选有效时间，可是这个表里的时间没有参考意义，不应该默认进行筛选

**Comment by ThomasChan** [comment]
哈哈咱们系统可没有那么 “智能” 的知道你这个时间字段没有参考意义哦，只有人才知道。

**Comment by zhaosy0415** [comment]
那咱们系统是怎么“智能”的在我几十个时间字段里面选择一个作为筛选条件呢？
![image](https://user-images.githubusercontent.com/39791844/42358595-f59a7278-810f-11e8-80a2-39f6a65cc1c3.png)

**Comment by ThomasChan** [comment]
如果有时间字段的话就选第一个呀😂

**Comment by zhaosy0415** [comment]
那也可以一个都不选呀~默认都是无呀~因为选择错误的字段还要再进行修改也蛮麻烦的呢~
