### ISSUE TITLE
邓凯红-时间字段按月统计时，图表坐标轴改为xxxx年x月

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#185]
![image](https://user-images.githubusercontent.com/39791844/42356232-f3986ab8-8103-11e8-8b6c-20b8620eb44e.png)
步骤：
1.维度时时间字段，统计方式是按月
结果：
1.坐标轴的显示格式如图
期望：
2018-03-01显示为2018年3月或者其他类似方式，不要显示到具体日
2017-12-01显示为2017年12月或者其他类似方式，不要显示到具体日

**Comment by ThomasChan** [comment]
之前是有个 bug 没有保存住格式，已经改过了，旧的图重新选择一下那个轴吧

**Comment by zhaosy0415** [comment]
修改成柱状图可以或者折线图，可以显示为xxxx年x月，但是多选柱状图还是显示为2017-12-03这种格式

**Comment by wwgracie** [comment]
@ThomasChan 多选柱状图还没改过来
