### ISSUE TITLE
司宇：筛选的条件和展示的内容不符

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#186]
http://52.83.102.127:8090/#/app/51/dashboard/62/chart/802
![image](https://user-images.githubusercontent.com/39791844/42357984-17d342c8-810d-11e8-9bb9-8813ed5f8205.png)
![image](https://user-images.githubusercontent.com/39791844/42357994-25c33834-810d-11e8-9170-4a88df89fdf3.png)
没有在筛选条件中勾选的内容还是显示在图表中

**Comment by wwgracie** [comment]
@zhaosy0415 点下面的“应用”按钮才会生效

**Comment by zhaosy0415** [comment]
![070601](https://user-images.githubusercontent.com/39791844/42365624-990facea-8131-11e8-8d50-51667817ff7b.gif)
是点击了应用之后没有生效才提的bug，能否先验证一下？

**Comment by wwgracie** [comment]
@ThomasChan  看一下

**Comment by firelyu** [comment]
去掉“排除”的过滤条件后，“包含”的过滤条件才能正常生效

**Comment by ThomasChan** [comment]
等部署后验证
