### ISSUE TITLE
【bug】司宇：使用DAYOFWEEK，返回的星期不正确

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#19]
![image](https://user-images.githubusercontent.com/39791844/41030309-9bd0024c-69b0-11e8-9d17-e70321a1389d.png)

![image](https://user-images.githubusercontent.com/39791844/41030292-92b60d96-69b0-11e8-98a0-3873c499fd81.png)

**Comment by cyberyoung** [comment]
这个是因为MySQL将周日作为一周的第一天
我们可以统一处理下

**Comment by zhaosy0415** [comment]
验证通过
