### ISSUE TITLE
杨慧: 设置了两个权限控制条件,结果是交集而不是并集

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#192]
添加了两个权限,一个是用户A,但没有选择筛选条件.第二个是用户A,筛选条件为之能看到某一条订单内容.结果A依然只能看到某一条订单的内容.由此可见A的权限是由最小的权限来决定的.

**Comment by meredith620** [comment]
问题确认,下个版本会修复. 
是多条规则中, 空规则会被忽略, 容易被理解成"或"关系没有生效.
其实规则间依然是"或"关系, 非空规则可继续使用.
