### ISSUE TITLE
已在仪表盘中使用计算字段可删除-dll

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#193]
步骤：
1、添加计算字段A，使用该字段作图
2、新chart中删除计算字段A

结果：
可删除

期望：
不可删除，给提示。

**Comment by linhualai** [comment]
@zhaosy0415 
从我们设计的出发点, 计算字段是一个 ad-hoc , 自由灵活添加的一个过程. 

它能够复用只是一个历史上的“用过”的原因, 给它提供一个快捷方式. 它在逻辑上并没有和正在chart上使用的metric有一个强关联的关系. 所以这个应该不是一个问题.

**Comment by zhaosy0415** [comment]
![default](https://user-images.githubusercontent.com/39791844/43827374-491dea84-9b2c-11e8-87d9-2c6f8aacbf37.gif)
