### ISSUE TITLE
图表前端不显示-dll

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#20]
步骤：
1、多选柱状图/折线图选择维度和数值
2、添加筛选条件实收金额！=0

结果：
1、只有数值，不显示图表  图1&图2
2、显示图表 图3
期望：
不加筛选条件也显示图表

图1
![image](https://user-images.githubusercontent.com/39791844/41030263-7ffb3fa0-69b0-11e8-90ce-c132b551156e.png)
图2
![image](https://user-images.githubusercontent.com/39791844/41030369-c4fcd316-69b0-11e8-8548-77c6edfd270a.png)
图3
![image](https://user-images.githubusercontent.com/39791844/41031207-b79aa822-69b2-11e8-8046-75e647faaa28.png)

**Comment by ThomasChan** [comment]
如何复现？

**Comment by ThomasChan** [comment]
使用如下测试数据无法复现
```
dimension,metric
测试1,343124
测试2,
测试3,4321
测试3,
测试4,3124
测试4,
测试5,34321
测试6,21432
测试7,
测试8,
测试8,4321
测试9,
测试10,43214
测试11,
测试12,13421
测试13,
测试14,3413
```

**Comment by cyberyoung** [comment]
并且翻台率不在筛选里
