### ISSUE TITLE
司宇：时间不能筛选同一天，需要选择一下日期之后再选择同一天

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#209]
![image](https://user-images.githubusercontent.com/39791844/42628533-fc2c317e-8602-11e8-802b-3c790bfe9e89.png)
![image](https://user-images.githubusercontent.com/39791844/42628571-1c37534a-8603-11e8-97ce-3fbbd3799cf8.png)

**Comment by ThomasChan** [comment]
请在下次部署后验证。
