### ISSUE TITLE
司宇：使用MONTH期望返回的是单独的月份的数字

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#21]
![image](https://user-images.githubusercontent.com/39791844/41030643-54e8e442-69b1-11e8-8e39-35462f123063.png)
![image](https://user-images.githubusercontent.com/39791844/41030702-7600ff7a-69b1-11e8-8a11-a9d01375cff4.png)

**Comment by zhaosy0415** [comment]
season同理

**Comment by iamtianyuan** [comment]
应该用`monthofyear`函数

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/41144197-aa718f94-6b2e-11e8-8f1c-e9549e89c4c2.png)
没有monthofyear这个函数

**Comment by iamtianyuan** [comment]
没有列出来，你先直接用吧，后面会加上的 ;)

**Comment by zhaosy0415** [comment]
使用了之后报错
![image](https://user-images.githubusercontent.com/39791844/41149363-f0059f8c-6b3d-11e8-9c6d-ca9ebc10f5e8.png)

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/41266278-dc89a258-6e28-11e8-879e-9968f733ee84.png)
返回的月份不正确，使用monthofyear
http://52.83.102.127:8090/#/app/8/dashboard/9/chart/93

**Comment by iamtianyuan** [comment]
这个结果不是bug，红框中的那一行其实真实时间是在5月份，之所以显示成2018-04-30是因为这一天是属于从2018-04-30开始的这一周，这个图表上的数据是按照`周`来分组的。
月份那一列得到的结果是对的。
