### ISSUE TITLE
杨慧:多选柱状图显示结果不正确

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#210]
![image](https://user-images.githubusercontent.com/39791844/42682181-663e614a-86bc-11e8-8533-ff4fecdb545d.png)
如图.数值营业额比净收入要大,但是图表显示则是反的.

**Comment by wwgracie** [comment]
@zhaosy0415  还是因为刻度问题，两个刻度设置成一样的，就不会有这个问题了。
