### ISSUE TITLE
宋洪彪：重置密码一直显示邮箱或密码错误

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#212]
重复多次后，一直显示5分钟后请重试，是否可以倒计时；点击忘记密码，显示：系统没有配置邮箱服务，请找管理员修改密码，是否可以邮箱重置密码

**Comment by MarshallChen** [comment]
第一个问题我没明白您的意思；第二个问题是当提示系统没有配置邮箱服务是不能通过邮箱找回密码的，只能管理员修改当前用户密码然后把密码告诉给用户。

**Comment by wwgracie** [comment]
@zhaosy0415  这个问题还能复现吗？

**Comment by wwgracie** [comment]
@zhaosy0415  重置密码时要点保存，保存之后，重置的密码才生效，才可以登录。
