### ISSUE TITLE
邓凯红-以前添加的计算字段，这次更新后报错，新添加计算字段也报错

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#215]
![image](https://user-images.githubusercontent.com/39791844/42854641-666bca48-8a6f-11e8-8921-86e2f56e0302.png)
![image](https://user-images.githubusercontent.com/39791844/42854713-c4186872-8a6f-11e8-8ffe-a786c571fa81.png)
![image](https://user-images.githubusercontent.com/39791844/42854732-e3040962-8a6f-11e8-8a07-2033a04ea23e.png)

**Comment by janplus** [comment]
烦请提供一下涉及的数据集以及图表的链接。

**Comment by zhaosy0415** [comment]
http://52.83.102.127:8090/#/app/49/dashboard/57
下图是点进去前，编辑移除后，再添加就报错
http://52.83.102.127:8090/#/app/49/dashboard/57/chart/745

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/42863442-cc640704-8a95-11e8-97c7-6673c5f571a3.png)

**Comment by zhaosy0415** [comment]
数据集：http://52.83.102.127:8090/#/app/49/dataset/677

**Comment by zhaosy0415** [comment]
另一处
http://52.83.102.127:8090/#/app/50/dashboard/56/chart/705
![image](https://user-images.githubusercontent.com/39791844/42863727-a18d08ae-8a96-11e8-82ed-bd09929c7757.png)
红框里的都是计算字段现在都报错，按照同样的公式添加新的计算字段时在点击下一步就会报错

**Comment by janplus** [comment]
应用「外卖Demo」中的「菜品情况」能提供Excel文件给我测试么？

**Comment by janplus** [comment]
另，我使用 `dll@acewill.cn` 账号登录无法访问 app 49，能把 app 49 协作给 `dll@acewill.cn` 么

**Comment by zhaosy0415** [comment]
我提供另外一个Excel吧
在这个Excel创建图表添加计算字段，最简单的sum函数都报错
![image](https://user-images.githubusercontent.com/39791844/42864572-84b1c4d8-8a99-11e8-98e0-085c8f274677.png)

**Comment by janplus** [comment]
好的，烦请提供一下。

**Comment by zhaosy0415** [comment]
1、49已协作给dll
2、怎么把Excel提供给你，你微信是？

**Comment by janplus** [comment]
[中学.xlsx](https://github.com/henglabs/issues/files/2204821/default.xlsx)

像这样点击如下图的按钮直接上传到 issue 里面即可。

![image](https://user-images.githubusercontent.com/3134769/42866707-f2e2d6b2-8a9f-11e8-84c7-2246debe2d7f.png)

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/42867446-39fb77aa-8aa2-11e8-9007-38cc0441cc34.png)
这6个表追加文件上传到衡石的
太大了，不能超过10M

**Comment by janplus** [comment]
可以邮件到：wujian@hengshi.com

**Comment by zhaosy0415** [comment]
已发送

**Comment by zhaosy0415** [comment]
我点击编辑原来的计算字段，发现里面的公式都是空的，所以报错
![image](https://user-images.githubusercontent.com/39791844/42872030-5b2ccb66-8aae-11e8-98c2-4c671ae8ebe1.png)

**Comment by janplus** [comment]
几个问题：

1. 图表中聚合新增列报错的问题

这是因为聚合的新增列本身就是一个聚合列，这是不允许的，新版本已经禁止了。

2. 数据集类型问题

http://52.83.102.127:8090/#/app/50/dataset/681 的一些列类型为 unknown，烦请提供下这个Excel我再调试一下问题

3. 编辑原有的计算字段，发现里面的公式是空的

未发现这个情况，如果你那边有这个情况，烦请提供下数据集链接以及列名

**Comment by zhaosy0415** [comment]
2、http://52.83.102.127:8090/#/app/50/dataset/681 的Excel文件
[外卖最终做图表标准菜品17 2个月的.xlsx](https://github.com/henglabs/issues/files/2209318/17.2.xlsx)
3、以下图红框中的数据为数据源创建一个图表，可以查看到原来建的计算字段，点击编辑，就会看到里面的公式都是空的
![image](https://user-images.githubusercontent.com/39791844/42935049-45027336-8b7b-11e8-9fb6-36b049fec68e.png)

**Comment by zhaosy0415** [comment]
1、图表中聚合新增列报错的问题
这是因为聚合的新增列本身就是一个聚合列，这是不允许的，新版本已经禁止了。

请问这个是什么意思？

**Comment by janplus** [comment]
> 1、图表中聚合新增列报错的问题
这是因为聚合的新增列本身就是一个聚合列，这是不允许的，新版本已经禁止了。
请问这个是什么意思？

如果你新增了一列包含了聚合函数如 sum、 count，那么这一列就不允许作为聚合计算列了。

**Comment by zhaosy0415** [comment]
哦，这样啊，这也是我新提的一个bug，你们应该设计为自动识别聚合函数，做度量时让他自动调整为无的，而不是需要我移除再添加一次

**Comment by wwgracie** [comment]
这个问题还在fix，下周应该能好。

**Comment by janplus** [comment]
> 2、http://52.83.102.127:8090/#/app/50/dataset/681 的Excel文件
外卖最终做图表标准菜品17 2个月的.xlsx

这个 excel 文件前1000行都是空行，所以探测不到类型，你可以手动删除前面的空行后上传就不会有问题了

> 3、以下图红框中的数据为数据源创建一个图表，可以查看到原来建的计算字段，点击编辑，就会看到里面的公式都是空的

下一个更新版本就不会有这个问题了
