### ISSUE TITLE
杨慧:[block]数据集为未知类型而且不能修改

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#225]
![default](https://user-images.githubusercontent.com/39791844/43053772-04d6600e-8e61-11e8-87b9-53470dca9771.gif)
http://52.83.102.127:8090/#/app/77/dataset/844

**Comment by janplus** [comment]
和 https://github.com/henglabs/issues/issues/215#issuecomment-408293543 应该是同样的问题

你把上传文件中前面的空行删掉重新上传就没有问题了。
