### ISSUE TITLE
杨慧:[block]去重计数结果不准确

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#228]
![image](https://user-images.githubusercontent.com/39791844/43069236-30473cb6-8e9f-11e8-99a7-fae68607488b.png)
![image](https://user-images.githubusercontent.com/39791844/43069246-3956c222-8e9f-11e8-99e9-84a552b57657.png)

**Comment by wwgracie** [comment]
@zhaosy0415  给的图看不出来是否正确，能把数据集连接贴出来吗？

**Comment by wwgracie** [comment]
@zhaosy0415  你是不是在数据集中添加的字段？应该在chart中添加字段，这样就会按分组来计数。

**Comment by linhualai** [comment]
@zhaosy0415 如 @wwgracie 所说的, 在数据集中计算的distinct count计数是整个数据集的计数.
如果要计算每个分组的计数可以在 chart 添加计算指标.
