### ISSUE TITLE
司宇：删除源表中添加的计算字段，进入数据管理报错

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#23]
步骤：
1. 在应用->功能验证->数据管理->o_order_history中添加计算字段后删除计算字段
2. 再次进入表o_order_history
结果：
提示数据库错误
期望：
正常显示

![image](https://user-images.githubusercontent.com/39791844/41032869-3a3e2c14-69b7-11e8-8e6a-0c6f96dc44de.png)

**Comment by iamtianyuan** [comment]
这个是随便增加一个计算字段，然后删除就会报错吗？还是说在某个特定情况下才会出现？

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/41149103-43b19f92-6b3d-11e8-9aa7-b0caed029037.png)
在别的表里添加了字段删除并未报错，但是这个表一直在报错

**Comment by zhaosy0415** [comment]
已经不报错了
