### ISSUE TITLE
杨慧:数据集中得字段无法在筛选条件中显示

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#230]
![default](https://user-images.githubusercontent.com/39791844/43125520-e214232e-8f5c-11e8-859a-28c6b3b3c48a.gif)
url:http://52.83.102.127:8090/#/app/77/dashboard/131/chart/1249

**Comment by ThomasChan** [comment]
@linhualai  该数据集有 449 个字段   但是在 chart 里你只给了我 223 个字段

**Comment by imzhangjunjie** [comment]
已经修复,请等待下次部署
