### ISSUE TITLE
杨慧:列值分组的疑问

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#236]
1.要设置一个价格带,希望展示结果如下图所示
![image](https://user-images.githubusercontent.com/39791844/43253930-bcd1bd18-90f8-11e8-88ac-45051b03b2f6.png)
 但实际展示结果只代表了组别
![image](https://user-images.githubusercontent.com/39791844/43253950-ccbc5936-90f8-11e8-81a0-0b4b63adc6c5.png)

**Comment by wwgracie** [comment]
@zhaosy0415  把列值分组的每个分组名称改成0～8、8～15…… 就可以吧？

**Comment by hhmob** [comment]
@zhaosy0415 新建列值分组字段，类型选“文本”，分组的名称改成0～8、8～15……
