### ISSUE TITLE
杨慧:数据同步不及时,数据库查询有数据 但BI里面同一天数据显示不出来

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#237]
url:http://52.83.102.127:8090/#/app/60/dataset/822
http://52.83.102.127:8090/#/app/60/dataset/839
http://52.83.102.127:8090/#/app/60/dataset/863
http://52.83.102.127:8090/#/app/60/dataset/808
http://52.83.102.127:8090/#/app/60/dataset/798
http://52.83.102.127:8090/#/app/60/dataset/796

有的是直接导进来得表,有的sql查询数据已经更新倒最新 但bi图表展示依然不显示数据

**Comment by janplus** [comment]
新版本重新设计实现了刷新管理逻辑，等待下周的更新。
