### ISSUE TITLE
杨慧：分组柱状图，添加筛选门店之后度量刻度不能自动变化

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#240]
![gif3](https://user-images.githubusercontent.com/39791844/43622769-73f9ac18-9710-11e8-9682-65e028508fc2.gif)
选好维度和度量之后，假设只查看某个门店的信息，然后度量的值选择刻度的时候无法进行选择。

**Comment by hhmob** [comment]
已经在新版本里修复
