### ISSUE TITLE
杨慧:上传本地文件失败

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#241]
url:http://52.83.102.127:8090/#/app/89/import/upload
![gif4](https://user-images.githubusercontent.com/39791844/43630780-d75d6880-9733-11e8-9ddb-e59f9be8d033.gif)

**Comment by weishishuo** [comment]
这个文件能给我们一份吗？ @zhaosy0415 方便我们解决问题。

**Comment by weishishuo** [comment]
@zhaosy0415 不用了，所有文件都不能上传了。

**Comment by cyberyoung** [comment]
现在应该好了
下周部署的版本应该再没有这个问题
