### ISSUE TITLE
升级后协作表报错-dll

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#242]
http://52.83.102.127:8090/#/app/49/dashboard/57
code
:
15001
error
:
"error/sql-execution-error"
msg
:
"执行sql失败，原因  SQL: SELECT (cast("hs__c22" as text)) AS "hs_fb02", date_trunc('month', to_timestamp("hs__c11", 'YYYY-MM-DD HH24:MI:ss'))::date AS "hs_3403", (case when (2) != 0 then (sum((case when extract(day from to_timestamp("hs__c11", 'YYYY-MM-DD HH24:MI:ss'))::integer <= 4 and cast("hs__c12" as text) = '期初盘点' and CASE WHEN "hs__c16" ~ E'^\\s*[-+]?\\d*\\.?\\d+\\s*$' THEN cast("hs__c16" as decimal) ELSE NULL END = 1 and cast("hs__c21" as text) = '门店库房' and CASE WHEN "hs__c18" ~ E'^\\s*[-+]?\\d*\\.?\\d+\\s*$' THEN cast("hs__c18" as decimal) ELSE NULL END = 1 and CASE WHEN "hs__c19" ~ E'^\\s*[-+]?\\d*\\.?\\d+\\s*$' THEN cast("hs__c19" as decimal) ELSE NULL END = 1 then CASE WHEN "hs__c15" ~ E'^\\s*[-+]?\\d*\\.?\\d+\\s*$' THEN cast("hs__c15" as decimal) ELSE NULL END else 0 end) + (case when extract(day from to_timestamp("hs__c11", 'YYYY-MM-DD HH24:MI:ss'))::integer > 27 and cast("hs__c12" as text) = '期末盘点' and CASE WHEN "hs__c16" ~ E'^\\s*[-+]?\\d*\\.?\\d+\\s*$' THEN cast("hs__c16" as decimal) ELSE NULL END = 1 and cast("hs__c21" as text) = '门店库房' and CASE WHEN "hs__c18" ~ E'^\\s*[-+]?\\d*\\.?\\d+\\s*$' THEN cast("hs__c18" as decimal) ELSE NULL END = 1 then CASE WHEN "hs__c15" ~ E'^\\s*[-+]?\\d*\\.?\\d+\\s*$' THEN cast("hs__c15" as decimal) ELSE NULL END else 0 end))) / (2) end) * count(distinct date_trunc('month', to_timestamp("hs__c11", 'YYYY-MM-DD HH24:MI:ss'))::date) AS "hs_aad6" FROM "dataset_677" WHERE (date_trunc('month', to_timestamp("hs__c11", 'YYYY-MM-DD HH24:MI:ss'))::date IN ()) AND (to_timestamp("hs__c11", 'YYYY-MM-DD HH24:MI:ss') >= '2018-01-01' AND to_timestamp("hs__c11", 'YYYY-MM-DD HH24:MI:ss') < '2019-01-01') GROUP BY (cast("hs__c22" as text)), date_trunc('month', to_timestamp("hs__c11", 'YYYY-MM-DD HH24:MI:ss'))::date ORDER BY (cast("hs__c22" as text)) ASC NULLS LAST, date_trunc('month', to_timestamp("hs__c11", 'YYYY-MM-DD HH24:MI:ss'))::date ASC NULLS LAST limit 1000 ERROR: ERROR: syntax error at or near ")"↵  位置：1495"
version
:
"2.0.0-SNAPSHOT@290b6dc"

**Comment by xuyian252** [comment]
过滤器错误 date_trunc('month', to_timestamp("hs__c11", 'YYYY-MM-DD HH24:MI:ss'))::date **IN ()**
@ThomasChan
