### ISSUE TITLE
刘璐：外卖订单数据TIDB和BI系统里的条数不一致。

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#243]
有个部门需要统计分析商户外卖订单数据，每天会有脚本自动抽取前一天的数据导入TIDB,然后BI系统再通过SQL读取TIDB的数据进行展现，现在发现的问题是，相同的查询SQL在TIDB和BI系统返回的结果是不一致的，例如2018-07-24的无效订单数量，TIDB里是22，而BI系统查到的是15.  查询SQL如下：

select substring(b.createtime,1,10)as '时间',COUNT(b.amoid) as "退单数量"
from   alp_merchant_order b LEFT JOIN alp_address c on b.sid = c.sid 
   where  c.sname like "鳗鳗的爱%" and b.orderstatus in (8,18)  group by 1 order by 1 DESC

据那个部门的人员反馈，经常会有两边数据不一致的情况发生，已经引起了客户的质疑，希望尽快查找原因并解决问题。

**Comment by cyberyoung** [comment]
是否可以给一下BI系统对应的数据集是哪个？谢谢

**Comment by zhaosy0415** [comment]
数据集是mmda_open。

**Comment by cyberyoung** [comment]
``` id  |   title
-----+-----------
 916 | mmda_open
 890 | mmda_open
 822 | mmda_open
```
目前起这个名字的数据集有以上3个，麻烦确认是哪个ID？

**Comment by zhaosy0415** [comment]
是 916。

**Comment by cyberyoung** [comment]
1. 理论上，这个数据集是custom sql，我们对于custom sql并没有中间处理，直接放到数据源执行的
2. 生成的SQL为```SELECT d.时间, d.商家名称,d.平台,d.营业额,d.净收入,d.有效订单,d.商家承担,d.餐盒费,d.平台佣金,d.配送费,e.退单数量,e.退单金额 FROM (select substring(b.createtime,1,10)as 时间,c.sname as 商家名称, CASE b.source WHEN 10 THEN '饿了么' WHEN 9 THEN '美团' WHEN 5 THEN '百度' END as 平台 ,sum(b.totalprice) as 营业额,sum(b.shopfee) as 净收入,COUNT(b.amoid) as 有效订单,sum(a.shop_rate) as 商家承担 , sum(b.package_fee) as 餐盒费,sum(b.service_money) as 平台佣金 ,sum(b.order_delivery_pay) as 配送费 from (select amoid,sum(shop_rate) as shop_rate from alp_merchant_order_activity group by amoid ) a RIGHT JOIN alp_merchant_order b on a.amoid = b.amoid LEFT JOIN alp_address c on b.sid = c.sid where  c.sname like "鳗鳗的爱%"  and b.orderstatus not in (0,8,12,18) group by 1,2,3 order by 1 desc,2 asc) d LEFT JOIN (select substring(b.createtime,1,10)as 时间1,c.sname as 商家名称1, CASE b.source WHEN 10 THEN '饿了么' WHEN 9 THEN '美团' WHEN 5 THEN '百度' END as 平台1 ,(sum(b.realprice) +sum(b.order_delivery_pay))as 退单金额, COUNT(b.amoid) as 退单数量 from alp_merchant_order b LEFT JOIN alp_address c on b.sid = c.sid where  c.sname like "鳗鳗的爱%" and b.orderstatus in (8,18) group by 1,2,3 order by 1 desc) e on (e.时间1=d.时间 and e.商家名称1=d.商家名称 and e.平台1=d.平台)```。
    1. 如果加上07-24的时间条件，则为```SELECT d.时间, d.商家名称,d.平台,d.营业额,d.净收入,d.有效订单,d.商家承担,d.餐盒费,d.平台佣金,d.配送费,e.退单数量,e.退单金额 FROM (select substring(b.createtime,1,10)as 时间,c.sname as 商家名称, CASE b.source WHEN 10 THEN '饿了么' WHEN 9 THEN '美团' WHEN 5 THEN '百度' END as 平台 ,sum(b.totalprice) as 营业额,sum(b.shopfee) as 净收入,COUNT(b.amoid) as 有效订单,sum(a.shop_rate) as 商家承担 , sum(b.package_fee) as 餐盒费,sum(b.service_money) as 平台佣金 ,sum(b.order_delivery_pay) as 配送费 from (select amoid,sum(shop_rate) as shop_rate from alp_merchant_order_activity group by amoid ) a RIGHT JOIN alp_merchant_order b on a.amoid = b.amoid LEFT JOIN alp_address c on b.sid = c.sid where  c.sname like "鳗鳗的爱%"  and b.orderstatus not in (0,8,12,18) group by 1,2,3 order by 1 desc,2 asc) d LEFT JOIN (select substring(b.createtime,1,10)as 时间1,c.sname as 商家名称1, CASE b.source WHEN 10 THEN '饿了么' WHEN 9 THEN '美团' WHEN 5 THEN '百度' END as 平台1 ,(sum(b.realprice) +sum(b.order_delivery_pay))as 退单金额, COUNT(b.amoid) as 退单数量 from alp_merchant_order b LEFT JOIN alp_address c on b.sid = c.sid where  c.sname like "鳗鳗的爱%" and b.orderstatus in (8,18) group by 1,2,3 order by 1 desc) e on (e.时间1=d.时间 and e.商家名称1=d.商家名称 and e.平台1=d.平台) where d.时间='2018-07-24'```，直接在TiDB上执行，结果如Excel所示。[order.xlsx](https://github.com/henglabs/issues/files/2282550/order.xlsx)

    1. 里面的退款数量有NULL的情况，应该是left join的第二段`COUNT(b.amoid) as 退单数量 from alp_merchant_order b LEFT JOIN alp_address c`这里导致的
3. TiDB加上退菜数量，直接执行，和BI系统一致
```MySQL [crm_alipos_alipos]> select 时间 ,sum(退单数量) from  (SELECT d.时间, d.商家名称,d.平台,d.营业额,d.净收入,d.有效订单,d.商家承担,d.餐盒费,d.平台佣金,d.配送费,e.退单数量,e.退单金额 FROM (select substring(b.createtime,1,10)as 时间,c.sname as 商家名称, CASE b.source WHEN 10 THEN '饿了么' WHEN 9 THEN '美团' WHEN 5 THEN '百度' END as 平台 ,sum(b.totalprice) as 营业额,sum(b.shopfee) as 净收入,COUNT(b.amoid) as 有效订单,sum(a.shop_rate) as 商家承担 , sum(b.package_fee) as 餐盒费,sum(b.service_money) as 平台佣金 ,sum(b.order_delivery_pay) as 配送费 from (select amoid,sum(shop_rate) as shop_rate from alp_merchant_order_activity group by amoid ) a RIGHT JOIN alp_merchant_order b on a.amoid = b.amoid LEFT JOIN alp_address c on b.sid = c.sid where  c.sname like "鳗鳗的爱%"  and b.orderstatus not in (0,8,12,18) group by 1,2,3 order by 1 desc,2 asc) d LEFT JOIN (select substring(b.createtime,1,10)as 时间1,c.sname as 商家名称1, CASE b.source WHEN 10 THEN '饿了么' WHEN 9 THEN '美团' WHEN 5 THEN '百度' END as 平台1 ,(sum(b.realprice) +sum(b.order_delivery_pay))as 退单金额, COUNT(b.amoid) as 退单数量 from alp_merchant_order b LEFT JOIN alp_address c on b.sid = c.sid where  c.sname like "鳗鳗的爱%" and b.orderstatus in (8,18) group by 1,2,3 order by 1 desc) e on (e.时间1=d.时间 and e.商家名称1=d.商家名称 and e.平台1=d.平台) where d.时间='2018-07-24') t group by 时间;```
```+------------+-------------------+
| 时间       | sum(退单数量)     |
+------------+-------------------+
| 2018-07-24 |                15 |
+------------+-------------------+
1 row in set, 827 warnings (2.50 sec)
```

综上，应该是custom SQL的SQL语句本身有问题
