### ISSUE TITLE
司宇：创建图表，维度时间按周显示，显示的不是周，是日期

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#28]
![image](https://user-images.githubusercontent.com/39791844/41085042-6226f128-6a68-11e8-918a-5713890d3fbf.png)

步骤：
1. 选择数据集创建柱状图表，维度选择时间，按周分组
2. 选择金额为度量
3. 查看维度显示样式
结果：
显示为日期
期望：
显示为第几周

**Comment by ThomasChan** [comment]
这个 feature 加上了，旧的图的轴需要重新选择才能将结果显示为`第几周`

**Comment by zhaosy0415** [comment]
已修复
