### ISSUE TITLE
协作的数据源不能进行聚合操作

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#3]
**步骤：**
1. 用户A创建应用并添加数据集，协作给用户B
2. 用户B使用被协作的数据源进行数据聚合
3. 用户B自己创建应用并添加数据集，进行数据聚合
**结果：**
步骤2： 不能聚合，不能选择字段
步骤3： 可以聚合，可以选择字段
**期望：**
步骤2：可以聚合

**Comment by cyberyoung** [comment]
第一步中，协作的是应用？

**Comment by zhaosy0415** [comment]
把整个应用协作
![image](https://user-images.githubusercontent.com/39791844/41013770-51403ab6-697a-11e8-9cfe-494f87e62edd.png)

**Comment by cyberyoung** [comment]
我是问第一步是A协作“应用”给B吧？ 因为第二步写的是“被协作的数据源”，我理解产品中数据源是无法协作的

**Comment by zhaosy0415** [comment]
是把应用协作给B

**Comment by zhaosy0415** [comment]
验证通过
