### ISSUE TITLE
杨慧: 数据结构中关于 '类型'和'默认聚合'的疑问

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#32]
![image](https://user-images.githubusercontent.com/39791844/41090373-a519a4fe-6a76-11e8-9470-8e7840e69e8c.png)
1.'类型'字段有的匹配不准确,同样都是数字,有的就是文本有的就是数字,聚合的时候因为不能保存,所以的反反复复修改字段类型,一遍遍的重新聚合.
2.'默认聚合'可否去掉?实际上我不明白的是,前提我有很多字段,我不可能一个个检查,那假如'金额'默认聚合为计数,那么在我用这个字段进行仪表盘展示的时候是否就只能选择计数了,如下图
![image](https://user-images.githubusercontent.com/39791844/41090934-fc715476-6a77-11e8-899e-a6a55bf54731.png)

![image](https://user-images.githubusercontent.com/39791844/41091441-1f209742-6a79-11e8-91d1-c949fc1cd78b.png)

**Comment by cyberyoung** [comment]
1. 这个和数据源数据存储是有关联的，之前看到过，同样的字段，在TiDB不同表里，设置了不同的类型
    1. “聚合的时候因为不能保存,所以的反反复复修改字段类型,一遍遍的重新聚合.” 没看懂这句话。
1. 默认聚会只是“默认”，是为了方便做图时可以一键选择。这个是可以修改的。分别回答图中问题：
    1. 图1里面“实收金额”在维度上，只能选择分组，如果是度量，就可以选择其它聚合方式
    1. 图2里面的实收金额是文本类型，所以只能选择“计数”。注意看字段前面的图标，T代表是文本。你可以在数据集里修改这个字段的类型，改成数字或者整型，就可以采用别的聚合方式。

**Comment by zhaosy0415** [comment]
'聚合的时候因为不能保存,所以的反反复复修改字段类型,一遍遍的重新聚合. '这句话是说假如我要上传一张表,然后我选择我得数据库中某一张表,在进行到如第一张图所示的那一步后,这个类型不能正确匹配,就像实收金额明明是数值类型,但自动成了'文本'类型,如果字段很多,我们不能一个个查它们是什么类型把?这就导致在聚合或者做仪表盘得时候突然发现这个字段不能达成想要的结果时(比如时候金额肯定是要求和的,但因为自动选择类型的问题,只能计数),必须返回去重新修改该字段得类型,才能在进行之前得工作. 所以这个'类型'如果不能正确匹配,会导致重复工作量.
 第二点,默认聚合只是默认,那就是说假如某个字段默认聚合是求和,那么在做仪表盘的时候还是可以选择其他的方式是吗?

**Comment by cyberyoung** [comment]
1. 可以把相应的dataset id和字段名给我，我去查一下，大部分原因是因为原始数据库类型问题
2. 对，默认是为了方便用户，在创建数据集选择了默认的聚合方式，创建图表时选择此字段就会使用默认聚合方式，如果需要其它方式，则还需要手动选择

**Comment by zhaosy0415** [comment]
数据集id :  dataset/42
