### ISSUE TITLE
司宇：图表不能导出csv

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#33]
步骤：
1. 打开已经创建的图表，点击导出csv
结果：
导出失败
期望：
成功导出
![image](https://user-images.githubusercontent.com/39791844/41145313-4afad314-6b32-11e8-9751-e133a457f6d5.png)

**Comment by zhaosy0415** [comment]
png也不能导出
![image](https://user-images.githubusercontent.com/39791844/41148163-ea1bcefa-6b3a-11e8-9ed0-13d01be6503b.png)

**Comment by ThomasChan** [comment]
@cyberyoung  assigness 应该是谁？

**Comment by ThomasChan** [comment]
@janplus  api/apps/id/dashboards/id/charts/id/download 地址之前是为啥被注释了？
现在让 @zhaojunliRain 恢复了。

**Comment by ThomasChan** [comment]
@meredith620 在看截图的问题。

**Comment by meredith620** [comment]
@MarshallChen 在处理electroshot.js监听前端渲染chart后的事件问题

**Comment by wwgracie** [comment]
导出csv已经可以用了，截屏还没解决。

**Comment by meredith620** [comment]
截屏的bug在开发分支已经解决了, 在等一个依赖的feature一起合并,预计7月下旬的小版本会提供修复的版本
