### ISSUE TITLE
杨慧: 同环比不能使用

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#34]
如题,同环比都报如下错误.
![image](https://user-images.githubusercontent.com/501691/41209435-356a5faa-6d5e-11e8-8043-08f7ff6d1068.png)

**Comment by zhaosy0415** [comment]
{version: "1.2-SNAPSHOT@5f15e0a", code: 1,…}
code
:
1
msg
:
"NullPointerException: ↵java.lang.NullPointerException↵	at com.hengshi.nangaparbat.sql.vendor.EngineVendor.refine(EngineVendor.java:71)↵	at com.hengshi.nangaparbat.sql.vendor.EngineVendor.fetchSqlData(EngineVendor.java:42)↵	at com.hengshi.nangaparbat.sql.vendor.BaseVendor.fetchSqlData(BaseVendor.java:128)↵	at com.hengshi.nangaparbat.proxy.DatasetProxyImpl.fetchSqlData(DatasetProxyImpl.java:120)↵	at com.hengshi.nangaparbat.proxy.DatasetProxyImpl.fetchChartData(DatasetProxyImpl.java:134)↵	at com.hengshi.nangaparbat.service.impl.DatasetServiceImpl.getChartData(DatasetServiceImpl.java:634)↵	at com.hengshi.nangaparbat.service.impl.DatasetServiceImpl$$FastClassBySpringCGLIB$$7a630a50.invoke(<generated>)↵	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)↵	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)↵	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)↵	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)↵	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)↵	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)↵	at com.hengshi.nangaparbat.service.impl.DatasetServiceImpl$$EnhancerBySpringCGLIB$$d4a1c572.getChartData(<generated>)↵	at com.hengshi.nangaparbat.action.DashboardAction.getChartDataWithOptions(DashboardAction.java:502)↵	at com.hengshi.nangaparbat.action.DashboardAction$$FastClassBySpringCGLIB$$af9c4b54.invoke(<generated>)↵	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)↵	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)↵	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)↵	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)↵	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)↵	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)↵	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)↵	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)↵	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)↵	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)↵	at com.hengshi.nangaparbat.action.DashboardAction$$EnhancerBySpringCGLIB$$258e63cb.getChartDataWithOptions(<generated>)↵	at sun.reflect.GeneratedMethodAccessor551.invoke(Unknown Source)↵	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)↵	at java.lang.reflect.Method.invoke(Method.java:498)↵	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)↵	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)↵	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)↵	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)↵	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)↵	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)↵	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)↵	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)↵	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)↵	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)↵	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)↵	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)↵	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequ…at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)↵	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)↵	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)↵	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)↵	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)↵	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)↵	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)↵	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)↵	at com.hengshi.nangaparbat.shiro.UserContextFilter.doFilterInternal(UserContextFilter.java:55)↵	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)↵	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)↵	at com.hengshi.nangaparbat.shiro.CSRFFilter.doFilterInternal(CSRFFilter.java:52)↵	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)↵	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)↵	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)↵	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)↵	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)↵	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)↵	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)↵	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)↵	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)↵	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)↵	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)↵	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)↵	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)↵	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)↵	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)↵	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)↵	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)↵	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)↵	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)↵	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)↵	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)↵	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)↵	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)↵	at java.lang.Thread.run(Thread.java:748)↵"
version
:
"1.2-SNAPSHOT@5f15e0a

url：http://52.83.102.127:8090/#/app/2/dashboard/5/chart/62

**Comment by linhualai** [comment]
fixed @zhaosy0415
