### ISSUE TITLE
【block】司宇：创建图表页面崩溃

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#37]
http://52.83.102.127:8090/#/app/8/dashboard/6
![image](https://user-images.githubusercontent.com/39791844/41211211-5f71aca4-6d68-11e8-8e6f-0df690b3e2ca.png)

步骤：
1. 创建一个图表，选择表格样式，添加一个时间作为维度，一个门店作为对比
2. 增加一个维度，选择门店
结果：
页面freeze，刷新之后再进入图表页面崩溃
期望：
正常显示

**Comment by ThomasChan** [comment]
表格渲染大量数据时有性能问题，待解决。

**Comment by ThomasChan** [comment]
Block by henglabs/everest#1406

**Comment by ThomasChan** [comment]
现在 Table chart 有两个限制

1. 列数超过 5000 ，不进行渲染
2. 列数 乘 行数 超过 10万，不进行渲染，但是提供渲染前 10 行的选项

**Comment by zhaosy0415** [comment]
不能接受这样的限制，一年还有12个月，如果给客户展示经营明细，按月展示连一年的数据都显示不全

**Comment by zhaosy0415** [comment]
暂时接受，关闭bug
