### ISSUE TITLE
司宇：计算同期值报错

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#39]
http://52.83.102.127:8090/#/app/8/dashboard/8/chart/60
![image](https://user-images.githubusercontent.com/39791844/41211918-1effa252-6d6d-11e8-889c-768cd0bb8a50.png)
![image](https://user-images.githubusercontent.com/39791844/41212152-75f99f12-6d6e-11e8-924e-78c893f827aa.png)

步骤：
1. 创建图表，选择表格样式，选择时间维度，选择数值，设置为求和->同/环比，选择同期值
结果：
报错
期望：
显示正确的数值

**Comment by linhualai** [comment]
fixed @zhaosy0415

**Comment by zhaosy0415** [comment]
验证通过
