### ISSUE TITLE
杨慧: 探索里面的发布功能无法使用

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#40]
如图,首先在数据集中设置了一个权限，
数据集url:http://52.83.102.127:8090/#/app/2/dataset/42,
![image](https://user-images.githubusercontent.com/39791844/41215005-c799a526-6d80-11e8-8200-34116384a836.png)
给该数据集限定了xuxf只能看到测试门店12的数据，然后创建仪表盘
仪表盘url:http://52.83.102.127:8090/#/app/2/dashboard/5
![image](https://user-images.githubusercontent.com/39791844/41215052-005729ec-6d81-11e8-8de6-af55e9f97fdd.png)
创建完成后，进行发布，测试xuxf是否只能看到测试门店12的订单数，然而报错了
![image](https://user-images.githubusercontent.com/39791844/41215110-53c16318-6d81-11e8-96eb-fd9919d4de02.png)
但是xuxf并没有进行协作，然后依然是上图中的错误。

**Comment by zhaosy0415** [comment]
还是无法进行发布

**Comment by zyy528** [comment]
verified
