### ISSUE TITLE
司宇：累计计算，报错

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#41]
http://52.83.102.127:8090/#/app/8/dashboard/8/chart/60
![image](https://user-images.githubusercontent.com/39791844/41215263-1f76976c-6d82-11e8-8dcd-b93bfd6c2ce6.png)
步骤：
创建图表，选择表格样式，选择时间维度，选择数值，设置为求和->累计计算，选择按季度累计
结果：
报错
期望：
显示正确的数值

**Comment by zhaosy0415** [comment]
维度中包含门店名称

**Comment by linhualai** [comment]
fixed @zhaosy0415
