### ISSUE TITLE
司宇：移动计算，报错

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#43]
http://52.83.102.127:8090/#/app/8/dashboard/8/chart/60
![image](https://user-images.githubusercontent.com/39791844/41215408-ba371484-6d82-11e8-9891-fae8f8d95fc2.png)
步骤：
创建图表，选择表格样式，选择时间维度，选择数值，设置为求和->移动计算，选择前1个月后1个月，求和
结果：
报错
期望：
显示正确的数值

**Comment by linhualai** [comment]
fixed @zhaosy0415
