### ISSUE TITLE
筛选条件中对子项进行搜索，搜索项不存在会显示-dll

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#45]
步骤：
1、仪表盘筛选项-选择一个文本字段
2、输入一个不存在子项【不存在啊啊啊啊】

结果：
显示这个不存在子项，造成干扰。

期望：
提示不存在

![image](https://user-images.githubusercontent.com/39791844/41216370-aa4a648c-6d86-11e8-8a9b-72493836cd8c.png)

**Comment by cyberyoung** [comment]
这是一个设计上的考虑
由于表格可能会很大，出于性能考虑，导致我们在抽取distinct value的时候选取的行数有一定限制，所以这里的搜索框不仅是一个搜索框，而且是一个输入框，如果搜索框不存在于我们取到的value set里面时，我们会把输入作为一个用户填入的值放进来，也作为过滤项
