### ISSUE TITLE
杨慧:修改维度后的粒度,好几分钟没反应

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#47]
图片稍后上传
![image](https://user-images.githubusercontent.com/39791844/41217274-fce1c3a4-6d89-11e8-86ad-3e121c6e32a3.png)

**Comment by ThomasChan** [comment]
麻烦贴一下该图表 URL 地址

**Comment by linhualai** [comment]
是否已经fix? @zhaosy0415
