### ISSUE TITLE
【bug】dll-计算字段-if条件无法使用

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#5]
步骤：
1、数据管理/仪表盘中添加计算列
2、列名，文本字段
3、编辑表达式 【if({是否赠菜}=1,'是','否')】
4、下一步

结果：
无显示，报错

期望：
下一步成功显示是&否

![if](https://user-images.githubusercontent.com/39791844/41012887-67696442-6976-11e8-8593-47191e5fbdea.png)

**Comment by zhaosy0415** [comment]
【if({是否赠菜}=1,'是','否')】ok了
【if({测试门店名称} in ('测试门店1','测试门店2','测试门店3'),'华北','华东')】报错
code:1
msg:
"NullPointerException: ↵java.lang.NullPointerException↵	at com.hengshi.nangaparbat.hql.BaseEval.callContain(BaseEval.java:86)↵	at com.hengshi.nangaparbat.sql.SqlEval.evalFunction(SqlEval.java:110)↵	at com.hengshi.nangaparbat.hql.BaseEval.eval(BaseEval.java:175)↵	at com.hengshi.nangaparbat.hql.BaseEval.thenEval(BaseEval.java:153)↵	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)↵	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)↵	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)↵	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)↵	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)↵	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)↵	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)↵	at com.hengshi.nangaparbat.hql.BaseEval.eval(BaseEval.java:228)↵	at com.hengshi.nangaparbat.hql.BaseEval.lambda$evalFunction$0(BaseEval.java:103)↵	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)↵	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)↵	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)↵	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)↵	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)↵	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)↵	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)↵	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)↵	at com.hengshi.nangaparbat.hql.BaseEval.evalFunction(BaseEval.java:108)↵	at com.hengshi.nangaparbat.sql.SqlEval.evalFunction(SqlEval.java:120)↵	at com.hengshi.nangaparbat.hql.BaseEval.eval(BaseEval.java:175)↵	at com.hengshi.nangaparbat.hql.BaseEval.eval(BaseEval.java:222)↵	at com.hengshi.nangaparbat.sql.SqlEvalContext.nextSelect(SqlEvalContext.java:38)↵	at com.hengshi.nangaparbat.sql.DatasetSchemaProvider.exprToSql(DatasetSchemaProvider.java:62)↵	at com.hengshi.nangaparbat.sql.DatasetSchemaProvider.fieldToSql(DatasetSchemaProvider.java:110)↵	at com.hengshi.nangaparbat.sql.DatasetSchemaProvider.lambda$fieldsToSql$3(DatasetSchemaProvider.java:159)↵	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)↵	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)↵	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)↵	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)↵	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)↵	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)↵	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)↵	at com.hengshi.nangaparbat.sql.DatasetSchemaProvider.fieldsToSql(DatasetSchemaProvider.java:159)↵	at com.hengshi.nangaparbat.proxy.DatasetProxyImpl.fetchFieldsData(DatasetProxyImpl.java:88)↵	at com.hengshi.nangaparbat.proxy.DatasetProxyImpl.fetchFieldsData(DatasetProxyImpl.java:83)↵	at com.hengshi.nangaparbat.proxy.DatasetProxyImpl.verifyField(DatasetProxyImpl.java:204)↵	at com.hengshi.nangaparbat.service.impl.DatasetServiceImpl.verifyField(DatasetServiceImpl.java:604)↵	at com.hengshi.nangaparbat.service.impl.DatasetServiceImpl$$FastClassBySpringCGLIB$$7a630a50.invoke(<generated>)↵	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)↵	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)↵	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)↵	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)↵	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)↵	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)↵	at com.hengshi.nangaparbat.service.impl.DatasetServiceImpl$$EnhancerBySpringCGLIB$$1e540214.verifyField(<generated>)↵	at com.hengshi.nangaparbat.action.DatasetAction.newFieldVerify(DatasetAction.java:421)↵	at com.hengshi.nangaparbat.action.DatasetAction$$FastClassBySpringCGLIB$$1f2b6cb8.invoke(<generated>)↵	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)↵	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)↵	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)↵	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)↵	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)↵	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocat…at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)↵	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)↵	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)↵	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)↵	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)↵	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)↵	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)↵	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)↵	at com.hengshi.nangaparbat.shiro.UserContextFilter.doFilterInternal(UserContextFilter.java:55)↵	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)↵	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)↵	at com.hengshi.nangaparbat.shiro.CSRFFilter.doFilterInternal(CSRFFilter.java:52)↵	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)↵	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)↵	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)↵	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)↵	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)↵	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)↵	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)↵	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)↵	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)↵	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)↵	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)↵	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)↵	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)↵	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)↵	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)↵	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)↵	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)↵	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)↵	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)↵	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)↵	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)↵	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)↵	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)↵	at java.lang.Thread.run(Thread.java:748)↵"

version:"1.2-SNAPSHOT@fda3749"

**Comment by iamtianyuan** [comment]
公式应该写成
``` ifelse({是否赠菜}='1', '是', '否') ```
今天给你们的版本应该就可以了
