### ISSUE TITLE
杨慧:添加计算字段中,多个if函数嵌套会卡掉

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#51]
url: http://52.83.102.127:8090/#/app/2/dataset/42
多次加载失败,然后重新添加该计算字段依然无法使用
![image](https://user-images.githubusercontent.com/501691/41221352-7629ff40-6d96-11e8-961e-dd23adfa7e42.png)

而且关掉字段,重新添加计算字段,然后又开始转圈,刷新好几次也没用

**Comment by wwgracie** [comment]
应该已经fix了。
