### ISSUE TITLE
司宇：权限控制，增加了数据分配规则但是没有选择内容，点击保存，报错

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#53]
![image](https://user-images.githubusercontent.com/39791844/41223613-e2f518c0-6d9c-11e8-9905-9ceff3315f93.png)
![image](https://user-images.githubusercontent.com/39791844/41223626-ebd62434-6d9c-11e8-8d77-77a31a4b49d0.png)

步骤：
1. 选择数据集，进入权限控制
2. 创建规则，选择用户，点击数据
3. 在数据页面增加一条行权限控制，选好字段设置好条件
4. 再次点击加号，但是不选择任何内容
5. 预览并保存
结果：
报错
期望：
弹出提示，要设置条件

**Comment by zhaosy0415** [comment]
![default](https://user-images.githubusercontent.com/39791844/42011085-60d71502-7ac4-11e8-906a-6c09bc3a24f3.gif)

**Comment by zhaosy0415** [comment]
![default](https://user-images.githubusercontent.com/39791844/42011230-1d875162-7ac5-11e8-97ca-689bb75a1679.gif)

**Comment by zyy528** [comment]
verified

**Comment by zhaosy0415** [comment]
经验证，当添加了没有条件任何内容的条件并保存后，不会报错，只保存有内容的条件
