### ISSUE TITLE
杨慧: 仪表盘没有图表,但依然显示如下情况(excel表无法删除)

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#55]
http://52.83.102.127:8090/#/app/2

所有仪表盘里面的图表都删除了,但excel的表无法删除

**Comment by cyberyoung** [comment]
删除哪个excel表？这个app里有多个excel数据集

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/41276508-021fb466-6e57-11e8-92bf-e0d83d441b78.png)

**Comment by xuyian252** [comment]
这个app发布过吗？ @zhaosy0415

**Comment by zhaosy0415** [comment]
![default](https://user-images.githubusercontent.com/39791844/42016650-ee209aa4-7ade-11e8-99fd-1c02b77ab2d9.gif)

**Comment by cyberyoung** [comment]
![default](https://user-images.githubusercontent.com/501691/42019722-7159741e-7ae8-11e8-8c43-20341e75e109.gif)

**Comment by zhaosy0415** [comment]
@xuyian252 没有发布过.

**Comment by cyberyoung** [comment]
![image](https://user-images.githubusercontent.com/501691/42020593-dca7d4a2-7aea-11e8-90e6-b672eaac82ba.png)

看起来是应该发布过的

**Comment by wwgracie** [comment]
已经有删除提示了，删除提示有些词还需修改，等再次升级后会看到。

**Comment by wwgracie** [comment]
先删除发布，再删除数据集。

**Comment by zhaosy0415** [comment]
@wwgracie 发布,探索都没有,全删干净了,但是这个表格就是删除不了!

**Comment by xuyian252** [comment]
删除图表操作分为两步:发送请求更新图表所在的仪表盘->发送请求删除图表

导致该问题的原因:第一个更新请求成功，仪表盘和图表之间的逻辑关系被删除，但第二个请求失败，图表没有被删除。

最终结果:逻辑关系被删除导致在仪表盘里看不到该图表，但该图表实际没有被删除

解决方式：
修改图表删除接口的请求逻辑，将两个删除操作在同一次请求里执行
@zhaosy0415 @wwgracie
