### ISSUE TITLE
【critical】司宇：同样的图表，刷新几次，展示的样式不一致

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#58]
账号：zhaosy
密码：请咨询我
chart：http://52.83.102.127:8090/#/app/8/dashboard/9/chart/92

![061202](https://user-images.githubusercontent.com/39791844/41266106-20696608-6e28-11e8-8c69-fbc0cc53af06.png)
![061201](https://user-images.githubusercontent.com/39791844/41266105-200f4d76-6e28-11e8-93b4-96f4f34f4289.png)

**Comment by cyberyoung** [comment]
我刷新都没问题诶……

**Comment by zhaosy0415** [comment]
多刷新几次，有惊喜

**Comment by cyberyoung** [comment]
这个是由于结果集超过了1k，gp返回顺序随机导致的
目前的解决方案是散点图按照group by排序，返回结果固定
从逻辑上，这个方案有一定的问题，就是可能错过某些异常值；从概率上，应该可以接受
