### ISSUE TITLE
【block】自己账号数据管理看不到自己刚上传的文件-邓凯红

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#59]
步骤：
1.上传Excel文件，显示成功

结果：
1.数据管理看不到，别人的账号可以看到我的上传

期望：
可以看到自己上传的文件

**Comment by cyberyoung** [comment]
给一下dataset的id

**Comment by zhaosy0415** [comment]
http://52.83.102.127:8090/#/app/18

**Comment by cyberyoung** [comment]
这个是APP的，数据集叫什么名字？

**Comment by zhaosy0415** [comment]
我看不到数据集，应用名字叫“运营驾驶舱”，上传的数据有7、8个名字叫：出库数据、入库数据、库存明细表、库存预警、采购单价和公共数据关联分析、原料投诉次数金额、菜品耗料表-1、菜品耗料表-2

**Comment by zhaosy0415** [comment]
![1528712857 1](https://user-images.githubusercontent.com/39791844/41272814-4f05e826-6e49-11e8-8621-6a6c1e5a095a.jpg)

**Comment by zhaosy0415** [comment]
![1528783289 1](https://user-images.githubusercontent.com/39791844/41272852-716030f2-6e49-11e8-9084-b2b5037feb4c.jpg)

**Comment by cyberyoung** [comment]
你的用户名是啥？密码如果可以也给一下，我方便去看看

**Comment by zhaosy0415** [comment]
用户名：dengkh
密码： gaoxiong
