### ISSUE TITLE
杨慧: [bug] 源表和fusion表不能进行聚合

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#6]
源表要左关联fusion表,但是找不到fusion表,两个表都进行了engine,但依然找不到.

**Comment by cyberyoung** [comment]
源表和fusion表都导入了Engine，是吗？
可以截图给我们看看吗？

**Comment by cyberyoung** [comment]
![image](https://user-images.githubusercontent.com/501691/41018340-dfef02a4-698b-11e8-881e-8c3419c943bb.png)
