### ISSUE TITLE
【block】司宇：导入Excel并再次替换数据后，制作图表，提示数据库错误

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#61]
![image](https://user-images.githubusercontent.com/39791844/41268316-08c493a6-6e32-11e8-9400-cc0f7bed8316.png)
![image](https://user-images.githubusercontent.com/39791844/41268510-015fe40c-6e33-11e8-8dbe-cf0e2ba45b6a.png)
步骤：
1. 导入Excel
2. 在数据管理中，替换数据
3. 制作热力图
结果：
提示数据库错误
期望：
正常显示
备注：
该表被替换过数据
http://52.83.102.127:8090/#/app/18/dashboard/10/chart/96
http://52.83.102.127:8090/#/app/18/dataset/245

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/41892140-ac5470fa-7949-11e8-9a6b-bf767ee8093c.png)

**Comment by cyberyoung** [comment]
@weishishuo 这个数据集应该是文件的，导入了engine，没做cast，导致func失败
```
org.postgresql.util.PSQLException: ERROR: function date_trunc(unknown, character varying) does not exist
```
chart地址是http://52.83.102.127:8090/#/app/18/dashboard/10/chart/96
