### ISSUE TITLE
司宇：仪表盘名字有英文，显示不全

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#62]
![image](https://user-images.githubusercontent.com/39791844/41268584-6417f648-6e33-11e8-8900-6637509b5b29.png)

**Comment by zhaosy0415** [comment]
仍有问题
![image](https://user-images.githubusercontent.com/39791844/42144362-335a7336-7ded-11e8-899b-8ba07409859a.png)

**Comment by wwgracie** [comment]
我看到的是正常的，是不是也跟分辨率有关。@MarshallChen
<img width="1005" alt="2018-07-02 3 36 26" src="https://user-images.githubusercontent.com/38898981/42150873-bfad2d40-7e0d-11e8-86c8-0eeb7f7008c0.png">

**Comment by zhaosy0415** [comment]
全屏；分辨率1920*1080；请问可以兼容的分辨率是多少？

**Comment by MarshallChen** [comment]
不是分辨率的问题，windows与mac上对行高跟overflow hidden的渲染不同，这个我已经fix了，下个版本应该会好。 @zhaosy0415
