### ISSUE TITLE
杨慧:金额默认全为文本类型

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#69]
1.上传excel表格,然后做指标卡出现 url :http://52.83.102.127:8090/#/app/24/dashboard/12/chart/120
![image](https://user-images.githubusercontent.com/39791844/41277487-f0f8d232-6e59-11e8-9047-e034521f58ea.png)

2.接着又的返回去从头修改字段类型为数字,然后查看了下金额默认全都是文本类型
![image](https://user-images.githubusercontent.com/39791844/41277626-522c88be-6e5a-11e8-97b8-acaf90d9afa8.png)

**Comment by cyberyoung** [comment]
这个删掉了？找不到资源了

**Comment by linhualai** [comment]
文件见 #117

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/42008984-f3c17556-7aba-11e8-8a2f-a696af6194b8.png)
还是文本啊.资源删不删掉没有关系.关键是只要我上传一个数据集,然后进行到如图所示的那一步之后.就看到的还是文本.
