### ISSUE TITLE
【bug】司宇：数据聚合页面，点击返回按钮，报错

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#7]
步骤：
1. 进入应用->数据管理->新建数据集->聚合，点击返回按钮

结果：
报错

期望：
显示正常

**Comment by cyberyoung** [comment]
截个图我们看看？

**Comment by zhaosy0415** [comment]
刚刚截图一直上传不上去
![_20180606104844](https://user-images.githubusercontent.com/39791844/41013684-dddb08d0-6979-11e8-8e11-6b5d084500dc.png)

**Comment by weishishuo** [comment]
@MarshallChen 
http://192.168.211.4:9981/api/apps/22/datasets/create 
http://192.168.211.4:9981/api/apps/22/datasets/create/import/config
聚合页面返回怎么调这两个接口？应该返回app页面

**Comment by zhaosy0415** [comment]
验证通过
