### ISSUE TITLE
邓凯红-仪表盘里建好的图表总是消失不见

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#73]
步骤：
1.在应用“运营驾驶舱-总经理”的名为“总监驾驶舱”的仪表盘中，新建的几个图表
结果：
1.退出仪表盘后，再进去就看不到了
期望：
1.新建的图表，若没有删除要一直存在

**Comment by ThomasChan** [comment]
我看了一下   是  http://52.83.102.127:8090/api/apps/24/dashboards/12/charts 这个接口返回有些慢？有 2.2 MB 的数据，请求到返回要花 20 多秒的时间，并不是看不到了，而是还没等到看到。。。。
