### ISSUE TITLE
司宇：多选柱状图数值差异对比不明显

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#74]
![061206](https://user-images.githubusercontent.com/39791844/41279601-86aa6872-6e5f-11e8-9a6a-3361c6ade7ab.png)
![061207](https://user-images.githubusercontent.com/39791844/41279608-8aa7fc3c-6e5f-11e8-8fb5-faa7614747af.png)

**Comment by cyberyoung** [comment]
豪哥，合并y轴得加回来

**Comment by ThomasChan** [comment]
这个 issue 的解决方案目前有两种：
1. 上周加了一个 feature 是可以自定义每个数值的刻度范围，现在可以先通过手动设置数值的刻度范围来解决这个问题
2. 等 `合并数值轴刻度范围` 的功能加回来

**Comment by wwgracie** [comment]
两个数值的刻度设置相同时，对比就出来了。
