### ISSUE TITLE
【block】堆叠柱形图应该支持多个数值堆积

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#76]
其他产品

![061208](https://user-images.githubusercontent.com/39791844/41281125-377f295a-6e63-11e8-92bf-423c5e1d0c6b.png)

**Comment by hhmob** [comment]
这个我们讨论过了，您的需求归类在“分组XXX图”的实现里，这个可能会排在后面再做了

**Comment by ThomasChan** [comment]
- [x] 堆叠柱状图
- [x] 百分比堆叠柱状图
- [x] 横向堆叠柱状图
- [x] 横向百分比堆叠柱状图
