### ISSUE TITLE
杨慧:if函数嵌套循环使用

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#78]
sum(if()),
count(if()),
count(distinct(concat())),
count(distinct(if()))

**Comment by linhualai** [comment]
@zhaosy0415 你这么写是ok的.
<img width="557" alt="image" src="https://user-images.githubusercontent.com/1201463/41962209-04e59d92-7a27-11e8-92d7-c776d6900351.png">
<img width="729" alt="image" src="https://user-images.githubusercontent.com/1201463/41962222-0c922e8e-7a27-11e8-9be1-c8120d6217fb.png">
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/1201463/41962249-1e3bc58c-7a27-11e8-8e97-2c2c7e98e00a.png">
