### ISSUE TITLE
【block】司宇：添加对比之后，同环比数值有问题

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#80]
![061209](https://user-images.githubusercontent.com/39791844/41281991-6faf9e3e-6e65-11e8-89f3-5d8b1e77c791.png)

步骤：
1. 创建表格类型的图表，维度设置为时间，按周分组；数值设置为营业额，添加对比维度为门店
2. 再次在数值中添加一个营业额，选择求和->同/环比，选择对比相对日期，对比值，偏移到之前一周
3. 查看数值
结果：
数值不正确，并不是前一周的数值
期望：
显示正确的数值

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/41284151-112fda94-6e6b-11e8-8020-00f2e72bb9e7.png)
增加门店维度，也不正确

**Comment by linhualai** [comment]
@zhaosy0415 fixed. 图可能需要重新做一个. 或者在老图中删掉数值维度再加回来.
