### ISSUE TITLE
邓凯红-柱形图度量不显示日期字段，无法选择

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#83]
![image](https://user-images.githubusercontent.com/39791844/41284018-bd618728-6e6a-11e8-8a45-7211c0f00ff5.png)
步骤：
1.数据集里有日期字段，柱形图度量里不显示日期字段
结果：
1.度量无法选择日期字段
期望：
1.度量可以选择日期字段

**Comment by cyberyoung** [comment]
http://52.83.102.127:8090/#/app/24/dashboard/21/chart/380

![image](https://user-images.githubusercontent.com/501691/41589879-36f31e1c-73e8-11e8-88b8-ceabda476e0c.png)
![image](https://user-images.githubusercontent.com/501691/41589881-389aa6d6-73e8-11e8-87d4-20ee687500a0.png)

**Comment by cyberyoung** [comment]
度量不支持日期时间字段
但是在添加字段里可以
![image](https://user-images.githubusercontent.com/501691/41590435-8b8080a4-73e9-11e8-8c1e-9b4abfe33c56.png)
