### ISSUE TITLE
邓凯红-创建柱形图，度量选中一个数字字段后报错

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#88]
http://52.83.102.127:8090/#/app/24/dashboard/22/chart/229
![image](https://user-images.githubusercontent.com/39791844/41328693-0259004a-6efc-11e8-8519-05cdc048dcac.png)
步骤：
1.创建柱形图，度量：小计（求和）
结果：
1.报错，无法显示图形
期望：
1.可以显示图形，不要报错

**Comment by linhualai** [comment]
fixed. @zhaosy0415
