### ISSUE TITLE
公式计算错误-dll

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#89]
http://52.83.102.127:8090/#/app/5/dataset/492

毛利润收银字段计算错误
公式：sum({应收金额}) - sum({标准成本})
![image](https://user-images.githubusercontent.com/39791844/41328778-7eae95ec-6efc-11e8-8ea2-abc8f547a2aa.png)

**Comment by iamtianyuan** [comment]
你期望结果是什么样的呢?
