### ISSUE TITLE
杨慧 : 去重计算无法实现

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#90]
![image](https://user-images.githubusercontent.com/39791844/41328811-b81b39e8-6efc-11e8-8590-8ee28bd4843c.png)
 count(distinct(订单id))或者单纯的count()都不能计算

**Comment by iamtianyuan** [comment]
用`distinc_count()`函数

**Comment by zhaosy0415** [comment]
![image](https://user-images.githubusercontent.com/39791844/41334447-367393d8-6f18-11e8-9ff8-2c70f174fbf2.png)

**Comment by iamtianyuan** [comment]
sorry,写错了，应该是`distinct_count()`
