### ISSUE TITLE
编辑计算字段后，计算公式不显示-dll

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#91]
步骤：
http://52.83.102.127:8090/#/app/5/dataset/492
1、对已有计算公式进行编辑
2、不修改后关闭
3、再次编辑该字段

结果：
计算公式为空

期望：
显示该字段计算公式

**Comment by cyberyoung** [comment]
@MarshallChen 后端返回了expr，前端未显示
![screen](https://user-images.githubusercontent.com/501691/41590746-557b9772-73ea-11e8-8f47-2ab94adc779b.png)

**Comment by MarshallChen** [comment]
@linhualai GET `/api/apps/{app}/datasets/{dataset}/fields/{field}` 未返回 readableFormula
