### ISSUE TITLE
数据集和仪表盘添加列报错不统一-dll

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#92]
数据集里面正常汉字  仪表盘里的是机器码
但是数据集里也有机器码的情形。

**Comment by ThomasChan** [comment]
这可能说的是 `系统错误` 跟 `NullPointException` 的错误吧，`NullPointException` 不应该抛出来 @linhualai    或者说在 debug 模式下抛出来

**Comment by wwgracie** [comment]
应该已经fix了，如果重现可以报具体的bug。

**Comment by ThomasChan** [comment]
这个还没呢 @linhualai 安排一下这个事

**Comment by linhualai** [comment]
@ThomasChan 和你说的不是一个事情. 应该说的是 %2B => 汉字 => 乱码的问题

**Comment by ThomasChan** [comment]
@zhaosy0415  麻烦截个图贴上来吧，没看懂你说的是哪儿的错误。。。。。

**Comment by zhaosy0415** [comment]
请联系李旸，已经和旸总沟通过

**Comment by cyberyoung** [comment]
豪哥说得对
