### ISSUE TITLE
杨慧 : [block]数据追加的时候,数据集中的数据不能在图表中被引用,否则追加失败

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#93]
http://52.83.102.127:8090/#/app/24/dataset/488
要追加数据, 前提要保证没有用该数据集进行过创建图表,否则显示追加失败.但是数据是不断更新的,
然后删除所有用数据集创建的图表,显示这个
![image](https://user-images.githubusercontent.com/39791844/41333169-643ecd46-6f13-11e8-958c-aeb7ad8cbd93.png)

**Comment by weishishuo** [comment]
提示信息已经很明确了，新的数据的类型，和已经创建的图表使用的类型有冲突，如果随便追加，会破坏图表的。 具体的冲突，麻烦旸哥沟通下，能不能拿到那些数据。 @cyberyoung

**Comment by cyberyoung** [comment]
杨慧，你把复现的步骤，所用到的追加的数据集写明一下吧
