### ISSUE TITLE
杨慧: 图表设置展示格式不生效

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#94]
![image](https://user-images.githubusercontent.com/39791844/41334293-a9cbe674-6f17-11e8-8828-e2820aa4c9bc.png)
url :.83.102.127:8090/#/app/24/dashboard/12/chart/184
![image](https://user-images.githubusercontent.com/39791844/41334315-c13d61b6-6f17-11e8-9fd0-69b928d72a3a.png)

**Comment by zyy528** [comment]
verified
