### ISSUE TITLE
杨慧: 表格有多个列时,无法左右滑动

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#97]
添加很多列之后,后面的列无法显示.
url:http://52.83.102.127:8090/#/app/24/dashboard/12/chart/220
![image](https://user-images.githubusercontent.com/39791844/41346581-777f418a-6f39-11e8-86d7-eda4bcdc7f18.png)

**Comment by ThomasChan** [comment]
没看出来哪列没显示啊
