### ISSUE TITLE
司宇：外链管理里面，点击名称提示未找到文件

### ISSUE THREAD

**Issue by zhaosy0415** [henglabs/issues#99]
![061402](https://user-images.githubusercontent.com/39791844/41389214-106cbe76-6fc2-11e8-94e1-e277f64b29bd.png)

步骤：
1. 分享某一个仪表盘
2. 进入外链管理，点击名称
结果：
提示未找到文件
期望：
显示仪表盘

**Comment by xuyian252** [comment]
@zhaosy0415 是在分享仪表盘以后做了删除操作吗？
